module.exports = {
  ScopePath: {
    'bo.dashboard': ['/cong-thanh-toan'],
    // 'bo.ewalletStateBankReport.getBankPayment':['/cong-thanh-toan/ngan-hang-hop-tac'],
    'bo.accountMerchant.search': ['/cong-thanh-toan/tai-khoan', '/cong-thanh-toan/tai-khoan/[id]'],
    'bo.merchant.searchPending': ['/cong-thanh-toan/duyet-mc'],
    'bo.merchant.searchApprove': ['/cong-thanh-toan/quan-ly-mc'],
    'bo.transaction.search': ['/cong-thanh-toan/quan-ly-giao-dich'],
    'bo.transaction.viewOnly': ['/cong-thanh-toan/quan-ly-giao-dich'],
    'bo.reportMerchant.report': ['/cong-thanh-toan'],
    'bo.account.search': ['/cong-thanh-toan/quan-ly-nguoi-dung'],
    'bo.account.role': ['/cong-thanh-toan/quan-ly-nguoi-dung/tao-tai-khoan'],
    'bo.account.scope': [
      '/cong-thanh-toan/scope',
      '/cong-thanh-toan/quan-ly-nguoi-dung/tao-tai-khoan-theo-quyen',
    ],
    'bo.pending.list': [
      '/cong-thanh-toan/pending-list',
      '/cong-thanh-toan/pending-list/processing-flow',
    ],
    'bo.template.search': ['/cong-thanh-toan/quan-ly-template'],
    'bo.operator.messageMc': ['/cong-thanh-toan/message'],
    'bo.operator.systemConfig': ['/cong-thanh-toan/system-config'],
    'bo.settingDeposit.search': ['/cong-thanh-toan/deposit-manage'],
    'bo.merchant.update': ['/cong-thanh-toan/quan-ly-mc/[id]'],
    'bo.merchant.viewOnly': ['/cong-thanh-toan/quan-ly-mc'],
    'bo.transaction.searchMismatchTransaction.action': ['/cong-thanh-toan/quan-ly-chuyen-khoan'],
    'bo.revenueStatistics.search': ['/cong-thanh-toan/revenue-statistics'],
    'bo.crossCheck.merchant': [
      '/cong-thanh-toan/doi-soat-doanh-nghiep',
      '/cong-thanh-toan/doi-soat-doanh-nghiep/chuyen-tien',
      '/cong-thanh-toan/doi-soat-doanh-nghiep/chuyen-tien/[id]',
    ],
    'bo.service.smsemail': [
      '/cong-thanh-toan/email-sms/quan-ly',
      '/cong-thanh-toan/email-sms/mc',
      '/cong-thanh-toan/email-sms/lich-su',
    ],
    'bo.accountMerchant.passwordTemporary': ['/cong-thanh-toan/mat-khau-tam'],

    'bo.ewalletAccount.searchSessions': ['/vi-dien-tu/lich-su-dang-nhap'],

    'bo.supplier.search': ['/cong-thanh-toan/giao-dich-nha-cung-cap'],

    // 'bo.supportTicket.create': ['/cham-soc-khach-hang/them-ticket'],
    'bo.supportTicket.update': ['/cham-soc-khach-hang'],
    'bo.supportTicket.dashboard': ['/cham-soc-khach-hang/ticket'],
    'bo.managementCard.QueryManagementCard': ['/cong-thanh-toan/quan-ly-the'],
    'bo.account.role.search': ['/cong-thanh-toan/quan-ly-quyen'],
    'bo.account.scope.search': ['/cong-thanh-toan/scope'],
    'bo.eWallet.approvalKyc': ['/vi-dien-tu/approval-kyc'],
    'bo.eWallet.autoApprovalKyc': ['/vi-dien-tu/auto-approval-kyc'],
    'bo.emailSmsMerchant.sendSms': ['/cong-thanh-toan/notify'],
    'bo.eWalletTransactionBank.report': ['/vi-dien-tu/bao-cao-ngan-hang'],
    'bo.ewalletAccount.bankLinked': ['/vi-dien-tu/user/link-manager'],
    'bo.reportMerchant.reportMerchantAmount': ['/cong-thanh-toan/so-luong-merchants'],
    'bo.eWalletAnnouncement.eWalletAnnounceMerchant': ['/cong-thanh-toan/quan-li-email-merchant'],
    'bo.ewalletTransactionBo.search': ['/vi-dien-tu/lich-su-giao-dich'],
    'bo.ewalletAccount.reCheck': ['/vi-dien-tu/kiem-duyet-thong-tin'],
    'bo.eWalletPayment.getDepositBanks': ['/vi-dien-tu/nap-tien-chuyen-khoan-thu-cong'],
    'bo.eWalletPayment.getBanks': ['/vi-dien-tu/cau-hinh-chuyen-khoan-thu-cong'],
    'bo.ewalletTransactionBo.searchAlertLogs': ['/vi-dien-tu/monitor/alertLogs'],
    'bo.eWalletSocialPaymentBo.searchSocialPay': ['/vi-dien-tu/social-payment'],
    'bo.eWalletSocialPaymentBo.reportSocialPay': ['/vi-dien-tu/social-payment/report'],
    'bo.eWalletTransactionBank.ewalletTransactionBank': ['/vi-dien-tu/transaction-bank'],
    'bo.ewalletIsecReportBo.getListCode': ['/vi-dien-tu/isec'],
    'bo.ewalletIsecReportBo.reportByDayIsec': ['/vi-dien-tu/isec/report'],
    'bo.ewalletIsecReportBo.searchIsecBulk': ['/vi-dien-tu/isec/report-trans'],
    'bo.eWalletReport.topupPhone': ['/vi-dien-tu/nap-dien-thoai'],
    'bo.ewalletIsecReportBo.reportIsecByAccount': ['/vi-dien-tu/isec-report'],
    'bo.eWalletHistory.search': ['/vi-dien-tu/lich-su-vi'],
    'bo.ewalletAccount.search': ['/vi-dien-tu/thong-tin-khach-hang'],
    'bo.ewalletStateBankReport.reportPoboOrder': ['/vi-dien-tu/bao-cao-ngan-hang'],
    'bo.ewalletTransactionBo.topTransaction': ['/vi-dien-tu/quan-ly-top-giao-dich'],
    'bo.ewalletWordfilterBo.getList': ['/vi-dien-tu/quan-ly-loc-tu'],
    'bo.store.search': ['/cong-thanh-toan/quan-ly-cua-hang'],
    'bo.ewalletReport.reportManualBanking': ['/vi-dien-tu/thong-ke-ngan-hang'],
    'bo.eWalletReport.cardTelco': ['/vi-dien-tu/quan-ly-telco'],
    'bo.eWalletAnnouncement.message': ['/vi-dien-tu/thong-bao-khach-hang'],
    'bo.ewalletStateBankReport.reportAccountAmount': ['/vi-dien-tu/bao-cao-vi'],
    'bo.account.scopeMClist': ['/cong-thanh-toan/cong-thanh-toan/quan-ly-quyen-dashboard'],
    'bo.transaction.searchPayout': ['/cong-thanh-toan/dich-vu-chi-ho-rut-tien'],
    'bo.ewalletReport.reportKyc': ['/vi-dien-tu/bao-cao-kyc'],
    'bo.ewalletReport.reportSys': ['/vi-dien-tu/bao-cao-he-thong'],
    'bo.ewalletReport.reportCheckSum': ['/vi-dien-tu/accounting/ewallet/report'],
    'bo.eWalletTemplateBo.search': ['/vi-dien-tu/quan-ly-template'],
    'bo.ewalletStateBankReport.reportEwalletHistory': ['/vi-dien-tu/bao-cao-giao-dich'],
    'bo.eWalletHistory.appHistoryTransaction': [
      '/vi-dien-tu/thong-ke-vi/dich-vu-vi',
      '/vi-dien-tu/thong-ke-vi/dich-vu-vi/[id]',
    ],
    'bo.reportMerchant.getTopMerchant': ['/cong-thanh-toan/giao-dich-nhieu-nhat'],
    'bo.ewalletReport.reportUser': ['/vi-dien-tu/thong-ke-vi/thong-ke-nguoi-dung'],
    'bo.eWalletSupplier.report': [
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac',
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac/chi-tiet-estio',
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac/chi-tiet-ocb',
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac/chi-tiet-vnpay',
    ],
    'bo.merchant.searchAppraisalMc': [
      '/cong-thanh-toan/tham-dinh',
      '/cong-thanh-toan/tham-dinh/[id]',
    ],
    'bo.reportMerchant.countMessage': ['/cong-thanh-toan/thong-ke-giao-dich-ncc'],
    'bo.ewalletStateBankReport.reportPoboOrder': ['/cong-thanh-toan/bao-cao-thu-ho-chi-ho'],
    'bo.merchantEwallet.report': ['/cong-thanh-toan/bao-cao-so-du-doi-tac'],
    'bo.eWalletPaymeTransfer.manage': ['/vi-dien-tu/chuyen-vi', '/vi-dien-tu/chuyen-vi/[id'],
    'bo.ewalletAccount.supplierTransaction': ['/vi-dien-tu/giao-dich-nha-cung-cap'],
    'bo.ewalletAccount.getConnectedUser': ['/vi-dien-tu/quan-ly-lien-ket-vi'],
    'bo.merchant.searchAppraisalMc': [
      '/cong-thanh-toan/tham-dinh',
      '/cong-thanh-toan/tham-dinh/[id]',
    ],
    'bo.reportMerchant.countMessage': ['/cong-thanh-toan/thong-ke-giao-dich-ncc'],
    'bo.ewalletStateBankReport.reportPoboOrder': ['/cong-thanh-toan/bao-cao-thu-ho-chi-ho'],
    'bo.merchantEwallet.report': ['/cong-thanh-toan/bao-cao-so-du-doi-tac'],
    'bo.eWalletPaymeTransfer.manage': ['/vi-dien-tu/chuyen-vi', '/vi-dien-tu/chuyen-vi/[id'],
    'bo.advanceSalary.reportAdvanceSalary': ['/cong-thanh-toan/bao-cao-ung-luong'],
    'bo.advanceSalary.getAdvanceSalary': ['/cong-thanh-toan/danh-sach-ung-luong'],
    'bo.ewalletAccount.searchEmployee': ['/vi-dien-tu/quan-ly-tk-vi-nv-payme'],
  },
};
