module.exports = {
  ScopePath: {
    'bo.eWalletTransactionBank.report': ['/vi-dien-tu/bao-cao-ngan-hang'],
    'bo.ewalletReport.reportManualBanking': ['/vi-dien-tu/thong-ke-ngan-hang'],
    'bo.eWalletReport.cardTelco': ['/vi-dien-tu/quan-ly-telco'],
    'bo.ewalletIsecReportBo.reportIsecByAccount': ['/vi-dien-tu/bao-cao-isec'],
    'bo.eWalletReport.topupPhone': ['/vi-dien-tu/topup-phone'],
    'bo.ewalletAccount.search': ['/vi-dien-tu/thong-tin-khach-hang'],
    'bo.eWalletHistory.search': ['/vi-dien-tu/lich-su-vi'],
    'bo.ewalletAccount.reCheck': ['/vi-dien-tu/kiem-duyet-thong-tin'],
    'bo.eWallet.approvalKyc': ['/vi-dien-tu/duyet-kyc'],
    'bo.eWallet.autoApprovalKyc': ['/vi-dien-tu/duyet-kyc-tu-dong'],
    'bo.ewalletWordfilterBo.getList': ['/vi-dien-tu/word-fillter'],
    'bo.ewalletTransactionBo.search': ['/vi-dien-tu/lich-su-giao-dich'],
    'bo.ewalletAccount.searchSessions': ['/vi-dien-tu/lich-su-dang-nhap'],
    'bo.ewalletAccount.bankLinked': ['/vi-dien-tu/user/link-manager'],
    'bo.eWalletPayment.getDepositBanks': ['/vi-dien-tu/nap-tien-chuyen-khoan-thu-cong'],
    'bo.eWalletPayment.getBanks': ['/vi-dien-tu/cau-hinh-chuyen-khoan-thu-cong'],
    'bo.ewalletTransactionBo.searchAlertLogs': ['/vi-dien-tu/monitor/alertLogs'],
    'bo.eWalletSocialPaymentBo.searchSocialPay': ['/vi-dien-tu/social-payment'],
    'bo.eWalletSocialPaymentBo.reportSocialPay': ['/vi-dien-tu/social-payment/report'],
    'bo.eWalletTransactionBank.ewalletTransactionBank': ['/vi-dien-tu/transaction-bank'],
    'bo.ewalletIsecReportBo.getListCode': ['/vi-dien-tu/isec'],
    'bo.ewalletIsecReportBo.reportByDayIsec': ['/vi-dien-tu/isec/report'],
    'bo.ewalletIsecReportBo.searchIsecBulk': ['/vi-dien-tu/isec/report-trans'],

    'bo.eWalletSocialPaymentBo.searchSocialPay': ['/vi-dien-tu/quan-ly-link-thanh-toan'],
    'bo.eWalletSocialPaymentBo.reportSocialPay': ['/vi-dien-tu/quan-ly-link-thanh-toan/bao-cao'],
    'bo.eWalletTransactionBank.ewalletTransactionBank': ['/vi-dien-tu/giao-dich-ngan-hang'],
    'bo.ewalletIsecReportBo.getListCode': ['/vi-dien-tu/quan-ly-isec'],
    'bo.ewalletIsecReportBo.reportByDayIsec': ['/vi-dien-tu/quan-ly-isec/bao-cao-ngay'],
    'bo.ewalletIsecReportBo.searchIsecBulk': ['/vi-dien-tu/quan-ly-isec/bao-cao-giao-dich'],

    'bo.ewalletTransactionBo.topTransaction': ['/vi-dien-tu/quan-ly-top-giao-dich'],
    'bo.eWalletAnnouncement.message': ['/vi-dien-tu/thong-bao-khach-hang'],
    'bo.ewalletStateBankReport.reportAccountAmount': ['/vi-dien-tu/bao-cao-vi'],
    'bo.ewalletWordfilterBo.getList': ['/vi-dien-tu/quan-ly-loc-tu'],
    'bo.eWalletReport.linkedBank': ['/vi-dien-tu/bao-cao/lien-ket-ngan-hang'],
    'bo.ewalletStateBankReport.getBanks': ['/vi-dien-tu/ngan-hang-hop-tac'],
    'bo.ewalletReport.reportKyc': ['/vi-dien-tu/bao-cao-kyc'],
    'bo.ewalletAccount.getConnectedUser': ['/vi-dien-tu/quan-ly-lien-ket-vi'],
    'bo.eWalletSetting.config': ['/vi-dien-tu/van-hanh/he-thong'],
    'bo.eWalletTemplateBo.search': ['/vi-dien-tu/quan-ly-template'],
    'bo.ewalletReport.reportSys': ['/vi-dien-tu/bao-cao-he-thong'],
    'bo.ewalletAccount.supplierTransaction': ['/vi-dien-tu/giao-dich-nha-cung-cap'],
    'bo.eWalletSupplier.report': [
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac',
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac/chi-tiet-estio',
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac/chi-tiet-ocb',
      '/vi-dien-tu/tai-khoan/vi-dien-tu/doi-tac/chi-tiet-vnpay',
    ],
    'bo.ewalletFastLoan.getList': ['/vi-dien-tu/quan-ly-goi-vay'],
    'bo.ewalletAccount.searchEmployee': ['/vi-dien-tu/quan-ly-tk-vi-nv-payme'],
  },
};
