module.exports = {
  ScopePath: {
    'bo.dashboard': ['/cong-thanh-toan'],
    'bo.accountMerchant.search': ['/cong-thanh-toan/tai-khoan', '/cong-thanh-toan/tai-khoan/[id]'],
    'bo.merchant.searchPending': ['/cong-thanh-toan/duyet-mc'],
    'bo.merchant.searchApprove': ['/cong-thanh-toan/quan-ly-mc'],
    'bo.account.search': ['/cong-thanh-toan/quan-ly-nguoi-dung'],
    'bo.transaction.search': ['/cong-thanh-toan/transaction-manage'],
    'bo.transaction.viewOnly': ['/cong-thanh-toan/transaction-manage'],
    'bo.reportMerchant.report': ['/cong-thanh-toan'],
    'bo.account.role': ['/cong-thanh-toan/quan-ly-nguoi-dung/tao-tai-khoan'],
    'bo.account.scope': ['/cong-thanh-toan/quan-ly-nguoi-dung/tao-tai-khoan-theo-quyen'],
    'bo.pending.list': [
      '/cong-thanh-toan/pending-list',
      '/cong-thanh-toan/pending-list/processing-flow',
    ],
    'bo.template.search': ['/cong-thanh-toan/template-manage'],
    'bo.operator.messageMc': ['/cong-thanh-toan/message'],
    'bo.operator.systemConfig': ['/cong-thanh-toan/he-thong'],
    'bo.settingDeposit.search': ['/cong-thanh-toan/quan-ly-ky-quy'],
    'bo.merchant.update': ['/cong-thanh-toan/quan-ly-mc/[id]'],
    'bo.merchant.viewOnly': ['/cong-thanh-toan/quan-ly-mc'],
    'bo.revenueStatistics.search': ['/cong-thanh-toan/thong-ke-doanh-thu'],
    'bo.crossCheck.merchant': [
      '/cong-thanh-toan/doi-soat-doanh-nghiep',
      '/cong-thanh-toan/doi-soat-doanh-nghiep/chuyen-tien',
      '/cong-thanh-toan/doi-soat-doanh-nghiep/chuyen-tien/[id]',
    ],
    'bo.service.smsemail': [
      '/cong-thanh-toan/email-sms/quan-ly',
      '/cong-thanh-toan/email-sms/mc',
      '/cong-thanh-toan/email-sms/lich-su',
    ],
    'bo.supplier.search': ['/cong-thanh-toan/supplier'],
    'bo.reportMerchant.reportTopTransaction': ['/cong-thanh-toan/thong-ke-top'],
    'bo.account.role.search': ['/cong-thanh-toan/quan-ly-quyen'],
    'bo.account.scope.search': ['/cong-thanh-toan/quan-li-quyen'],
    'bo.emailSmsMerchant.sendSms': ['/cong-thanh-toan/gui-thong-bao'],
    'bo.transaction.searchMismatchTransaction.action': ['/cong-thanh-toan/quan-ly-chuyen-khoan'],
    'bo.reportMerchant.reportMerchantAmount': ['/cong-thanh-toan/quantity-merchants'],
    'bo.eWalletAnnouncement.eWalletAnnounceMerchant': ['/cong-thanh-toan/email-merchant'],
    'bo.store.search': ['/cong-thanh-toan/quan-ly-cua-hang'],
    'bo.account.scopeMClist': ['/cong-thanh-toan/cong-thanh-toan/quan-ly-quyen-dashboard'],
    'bo.transaction.searchPayout': ['/cong-thanh-toan/dich-vu-chi-ho-rut-tien'],
    'bo.managementCard.QueryManagementCard': ['/cong-thanh-toan/quan-ly-the'],
    'bo.reportMerchant.reportSDKIncome': ['/cong-thanh-toan/thong-ke-doanh-thu-sdk'],
    'bo.ewalletStateBankReport.reportPartner': ['/cong-thanh-toan/bao-cao-doi-tac'],
    'bo.reportMerchant.reportTransaction': ['/cong-thanh-toan/bao-cao-giao-dich'],
    'bo.merchantEwallet.searchBalanceMerchant': ['/cong-thanh-toan/lich-su-thay-doi-so-du'],
    'bo.ewalletStateBankReport.reportPoboOrder': ['/cong-thanh-toan/bao-cao-thu-ho-chi-ho'],
    'bo.merchantEwallet.report': ['/cong-thanh-toan/bao-cao-so-du-doi-tac'],
    'bo.historyAccountLogin.getList': ['/cong-thanh-toan/lich-su-dang-nhap'],
    'bo.ewalletStateBankReport.reportPoboOrder': ['/cong-thanh-toan/bao-cao-thu-ho-chi-ho'],
    'bo.ewalletStateBankReport.getBankPayment': ['/cong-thanh-toan/ngan-hang-hop-tac'],
    'bo.advanceSalary.reportAdvanceSalary': ['/cong-thanh-toan/bao-cao-ung-luong'],
    'bo.advanceSalary.getAdvanceSalary': ['/cong-thanh-toan/danh-sach-ung-luong'],
  },
};
