export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING_DATA_TABLE = 'HIDE_LOADING_DATA_TABLE';
export const SHOW_LOADING_DATA_TABLE = 'SHOW_LOADING_DATA_TABLE';
export const SHOW_LOADING_SKELETON = 'SHOW_LOADING_SKELETON';
export const HIDE_LOADING_SKELETON = 'HIDE_LOADING_SKELETON';
export const SERVER_ERROR_API = 'SERVER_ERROR_API';
export const CLEAR_STORE = 'CLEAR_STORE';

export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
export const GET_TRANSACTION_HISTORY_SUCCESS = 'GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_FAIL = 'GET_TRANSACTION_HISTORY_FAIL';

export const GET_LIST_PAYMENT_PAGE = 'GET_LIST_PAYMENT_PAGE';
export const GET_LIST_PAYMENT_PAGE_SUCCESS = 'GET_LIST_PAYMENT_PAGE_SUCCESS';
export const GET_LIST_PAYMENT_PAGE_FAIL = 'GET_LIST_PAYMENT_PAGE_FAIL';

export const GET_DETAIL_PAYMENT_PAGE = 'GET_DETAIL_PAYMENT_PAGE';
export const GET_DETAIL_PAYMENT_PAGE_SUCCESS = 'GET_DETAIL_PAYMENT_PAGE_SUCCESS';
export const GET_DETAIL_PAYMENT_PAGE_FAIL = 'GET_DETAIL_PAYMENT_PAGE_FAIL';

export const CREATE_PAYMENT_PAGE = 'CREATE_PAYMENT_PAGE';
export const CREATE_PAYMENT_PAGE_SUCCESS = 'CREATE_PAYMENT_PAGE_SUCCESS';
export const CREATE_PAYMENT_PAGE_FAIL = 'CREATE_PAYMENT_PAGE_FAIL';
export const CREATE_PAYMENT_PAGE_REFRESH = 'CREATE_PAYMENT_PAGE_REFRESH';

export const EDIT_PAYMENT_PAGE = 'EDIT_PAYMENT_PAGE';
export const EDIT_PAYMENT_PAGE_SUCCESS = 'EDIT_PAYMENT_PAGE_SUCCESS';
export const EDIT_PAYMENT_PAGE_FAIL = 'EDIT_PAYMENT_PAGE_FAIL';
export const EDIT_PAYMENT_PAGE_REFRESH = 'EDIT_PAYMENT_PAGE_REFRESH';

export const UPDATE_FIELD_PAYMENT_PAGE = 'UPDATE_FIELD_PAYMENT_PAGE';
export const UPDATE_FIELD_PAYMENT_PAGE_SUCCESS = 'UPDATE_FIELD_PAYMENT_PAGE_SUCCESS';
export const UPDATE_FIELD_PAYMENT_PAGE_FAIL = 'UPDATE_FIELD_PAYMENT_PAGE_FAIL';

export const SENT_NOTI_PAYME_PAGE_CUSTOMER = 'SENT_NOTI_PAYME_PAGE_CUSTOMER';
export const SENT_NOTI_PAYME_PAGE_CUSTOMER_SUCCESS = 'SENT_NOTI_PAYME_PAGE_CUSTOMER_SUCCESS';
export const SENT_NOTI_PAYME_PAGE_CUSTOMER_FAIL = 'SENT_NOTI_PAYME_PAGE_CUSTOMER_FAIL';
//PayME link
export const CREATE_PAY_ME_LINK = 'CREATE_PAY_ME_LINK';
export const CREATE_PAY_ME_LINK_BULK = 'CREATE_PAY_ME_LINK_BULK';

export const UPDATE_PAY_ME_LINK = 'UPDATE_PAY_ME_LINK';
export const GET_LIST_PAY_ME_LINK = 'GET_LIST_PAY_ME_LINK';
export const GET_DETAIL_PAY_ME_LINK = 'GET_DETAIL_PAY_ME_LINK';
export const SEND_EMAIL_PAY_ME_LINK = 'SEND_EMAIL_PAY_ME_LINK';
export const GET_INFO_ACCOUNT = 'GET_INFO_ACCOUNT';

// BUTTON
export const GET_LIST_PAYMENT_BUTTON = 'GET_LIST_PAYMENT_BUTTON';
export const GET_LIST_PAYMENT_BUTTON_SUCCESS = 'GET_LIST_PAYMENT_BUTTON_SUCCESS';
export const GET_LIST_PAYMENT_BUTTON_FAIL = 'GET_LIST_PAYMENT_BUTTON_FAIL';

export const CREATE_PAYMENT_BUTTON = 'CREATE_PAYMENT_BUTTON';
export const CREATE_PAYMENT_BUTTON_SUCCESS = 'CREATE_PAYMENT_BUTTON_SUCCESS';
export const CREATE_PAYMENT_BUTTON_FAIL = 'CREATE_PAYMENT_BUTTON_FAIL';

export const GET_DETAIL_PAYMENT_BUTTON = 'GET_DETAIL_PAYMENT_BUTTON';
export const GET_DETAIL_PAYMENT_BUTTON_SUCCESS = 'GET_DETAIL_PAYMENT_BUTTON_SUCCESS';
export const GET_DETAIL_PAYMENT_BUTTON_FAIL = 'GET_DETAIL_PAYMENT_BUTTON_FAIL';

export const UPDATE_STOCK_PAYMENT_BUTTON = 'UPDATE_STOCK_PAYMENT_BUTTON';
export const UPDATE_STOCK_PAYMENT_BUTTON_SUCCESS = 'UPDATE_STOCK_PAYMENT_BUTTON_SUCCESS';
export const UPDATE_STOCK_PAYMENT_BUTTON_FAIL = 'UPDATE_STOCK_PAYMENT_BUTTON_FAIL';

export const UPDATE_PAYMENT_BUTTON = 'UPDATE_PAYMENT_BUTTON';
export const UPDATE_PAYMENT_BUTTON_SUCCESS = 'UPDATE_PAYMENT_BUTTON_SUCCESS';
export const UPDATE_PAYMENT_BUTTON_FAIL = 'UPDATE_PAYMENT_BUTTON_FAIL';

export const SAVE_FIELD_CUSTOM = 'SAVE_FIELD_CUSTOM';
export const EDIT_FIELD_CUSTOM = 'EDIT_FIELD_CUSTOM';

export const UPDATE_PRESET_FIELD = 'UPDATE_PRESET_FIELD';
export const UPDATE_PRESET_FIELD_AMOUNT = 'UPDATE_PRESET_FIELD_AMOUNT';
export const UPDATE_FIELD_AMOUNT_BUY_NOW = 'UPDATE_FIELD_AMOUNT_BUY_NOW';

//Transaction
export const GET_LIST_TRANSACTION = 'GET_LIST_TRANSACTION';
export const GET_LIST_PAYMENT = 'GET_LIST_PAYMENT';
export const GET_LIST_ORDER = 'GET_LIST_ORDER';
export const GET_LIST_REFUND = 'GET_LIST_REFUND';
export const PAYMENT_REFUND = 'PAYMENT_REFUND';
//settlement
export const GET_LIST_SETTLEMENT = 'GET_LIST_SETTLEMENT';
export const GET_CROSS_CHECK = 'GET_CROSS_CHECK';
export const GET_MERCHANT_FEE = 'GET_MERCHANT_FEE';

//satistics
export const GET_SATISTICS = 'GET_SATISTICS';
export const GET_SATISTICS_SUCCESS = 'GET_SATISTICS_SUCCESS';
export const GET_SATISTICS_FAIL = 'GET_SATISTICS_SUCCESS';

//SETTING
export const SETING_PROFILE_GET = 'SETING_PROFILE_GET';
export const SETING_PROFILE_GET_SUCCESS = 'SETING_PROFILE_GET_SUCCESS';
export const SETING_PROFILE_GET_FAIL = 'SETING_PROFILE_GET_FAIL';

export const SETTING_PROFILE_UPDATE = 'SETING_PROFILE_UPDATE';
export const SETTING_PROFILE_UPDATE_SUCCESS = 'SETING_PROFILE_UPDATE_SUCCESS';
export const SETTING_PROFILE_UPDATE_FAIL = 'SETING_PROFILE_UPDATE_FAIL';

//customer
export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER';
export const GET_LIST_CUSTOMER_SUCCESS = 'GET_LIST_CUSTOMER_SUCCESS';
export const GET_LIST_CUSTOMER_FAIL = 'GET_LIST_CUSTOMER_FAIL';

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL';

//ticket
export const GET_LIST_TICKET = 'GET_LIST_TICKET';
export const GET_LIST_TICKET_SUCCESS = 'GET_LIST_TICKET_SUCCESS';
export const GET_LIST_TICKET_FAIL = 'GET_LIST_TICKET_FAIL';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL';

export const REPLY_TICKET = 'REPLY_TICKET';
export const REPLY_TICKET_SUCCESS = 'REPLY_TICKET_SUCCESS';
export const REPLY_TICKET_FAIL = 'REPLY_TICKET_FAIL';

export const GET_LIST_REPLY_TICKET = 'GET_LIST_REPLY_TICKET';
export const GET_LIST_REPLY_TICKET_SUCCESS = 'GET_LIST_REPLY_TICKET_SUCCESS';
export const GET_LIST_REPLY_TICKET_FAIL = 'GET_LIST_REPLY_TICKET_FAIL';

//payment method
export const LIST_PAYMENT_METHOD = 'LIST_PAYMENT_METHOD';
export const LIST_PAYMENT_METHOD_SUCCESS = 'LIST_PAYMENT_METHOD_SUCCESS';
export const LIST_PAYMENT_METHOD_FAIL = 'LIST_PAYMENT_METHOD_FAIL';
//Dashboard
export const GET_STATISTIC_DASHBOARD = 'GET_STATISTIC_DASHBOARD';

//HDDT
export const GET_ELECTRONIC_CONTRACT = 'GET_ELECTRONIC_CONTRACT';
export const GET_ELECTRONIC_CONTRACT_SUCCESS = 'GET_ELECTRONIC_CONTRACT_SUCCESS';
export const GET_ELECTRONIC_CONTRACT_FAIL = 'GET_ELECTRONIC_CONTRACT_FAIL';

//SENT SMS contract
export const SENT_SMS_CONTRACT = 'SENT_SMS_CONTRACT';
export const SENT_SMS_CONTRACT_SUCCESS = 'SENT_SMS_CONTRACT_SUCCESS';
export const SENT_SMS_CONTRACT_FAIL = 'SENT_SMS_CONTRACT_FAIL';

//sss
export const SIGNUP_CONTRACT = 'SIGNUP_CONTRACT';
export const SIGNUP_CONTRACT_SUCCESS = 'SIGNUP_CONTRACT_SUCCESS';
export const SIGNUP_CONTRACT_FAIL = 'SIGNUP_CONTRACT_FAIL';

//get list payout
export const GET_LIST_PAYOUT = 'GET_LIST_PAYOUT';
export const GET_LIST_PAYOUT_SUCCESS = 'GET_LIST_PAYOUT_SUCCESS';
export const GET_LIST_PAYOUT_FAIL = 'GET_LIST_PAYOUT_FAIL';

//create payout single
export const CREATE_PAYOUT_SINGLE = 'CREATE_PAYOUT_SINGLE';
export const CREATE_PAYOUT_SINGLE_SUCCESS = 'CREATE_PAYOUT_SINGLE_SUCCESS';
export const CREATE_PAYOUT_SINGLE_FAIL = 'CREATE_PAYOUT_SINGLE_FAIL';

//cancel payout
export const CANCEL_PAYOUT_SINGLE = 'CANCEL_PAYOUT_SINGLE';
export const CANCEL_PAYOUT_SINGLE_SUCCESS = 'CANCEL_PAYOUT_SINGLE_SUCCESS';
export const CANCEL_PAYOUT_SINGLE_FAIL = 'CANCEL_PAYOUT_SINGLE_FAIL';

//get security password
export const REQUEST_SECURITY_PASSWORD = 'REQUEST_SECURITY_PASSWORD';
export const REQUEST_SECURITY_PASSWORD_SUCCESS = 'REQUEST_SECURITY_PASSWORD_SUCCESS';
export const REQUEST_SECURITY_PASSWORD_FAIL = 'REQUEST_SECURITY_PASSWORD_FAIL';

//confirm security code
export const CONFIRM_PAYOUT_SECURITY = 'CONFIRM_PAYOUT_SECURITY';
export const CONFIRM_PAYOUT_SECURITY_SUCCESS = 'CONFIRM_PAYOUT_SECURITY_SUCCESS';
export const CONFIRM_PAYOUT_SECURITY_FAIL = 'CONFIRM_PAYOUT_SECURITY_FAIL';
//Payout bulk
export const GET_LIST_PAYOUT_BULK = 'GET_LIST_PAYOUT_BULK';
export const CREATE_PAYOUT_BULK = 'CREATE_PAYOUT_BULK';
export const GET_SECURITY_CODE_PAYOUT_BULK = 'GET_SECURITY_CODE_PAYOUT_BULK';
export const CONFIRM_PAYOUT_BULK = 'CONFIRM_PAYOUT_BULK';
export const CANCEL_PAYOUT_BULK = 'CANCEL_PAYOUT_BULK';
export const READ_FILE_EXCEL_PAYOUT_BULK = 'READ_FILE_EXCEL_PAYOUT_BULK';
