export const rejectKYCWallet = [
  'Hình ảnh giấy tờ tùy thân bị mờ. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh giấy tờ tùy thân bị loé sáng. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh giấy tờ tùy thân bị mất góc. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh không phải là giấy tờ tuỳ thân. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh giấy tờ tùy thân mặt trước và mặt sau giống nhau. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh giấy tờ tùy thân không chụp từ bản gốc. Vui lòng cập nhật và gửi duyệt lại.',
  'Giấy tờ tùy thân đã sử dụng đăng ký Ví. Vui lòng cập nhật và gửi duyệt lại',
  'Giấy tờ tuỳ thân hết hạn sử dụng. Vui lòng cập nhật và gửi duyệt lại.',
  'Giấy tờ tuỳ thân không còn giá trị sử dụng. Vui lòng cập nhật và gửi duyệt lại.',
  'Số trên giấy tờ tùy thân không rõ. Vui lòng cập nhật và gửi duyệt lại.',
  'Video xác thực khuôn mặt không giống giấy tờ tùy thân. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh giấy tờ tuỳ thân chụp từ màn hình thiết bị khác. Vui lòng cập nhật và gửi duyệt lại.',
  'Video xác thực khuôn mặt quay từ màn hình thiết bị khác. Vui lòng cập nhật và gửi duyệt lại.',
  'Video xác thực không rõ khuôn mặt. Vui lòng cập nhật và gửi duyệt lại.',
  'Giấy tờ tuỳ thân đã qua chỉnh sửa. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh xác thực khuôn mặt không rõ. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh xác thực khuôn mặt không giống giấy tờ tuỳ thân. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh xác thực khuôn mặt được chụp  từ màn hình thiết bị khác. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh giấy phép đăng ký Kinh Doanh bị mờ',
  'Hình ảnh giấy phép đăng ký Kinh Doanh bị loé sáng',
  'Hình ảnh giấy phép đăng ký Kinh Doanh bị mất góc',
  'Hình ảnh giấy phép đăng ký Kinh Doanh không còn giá trị sử dụng',
  'Hình ảnh giấy phép đăng ký Kinh Doanh nghi ngờ giả mạo',
  'Hình ảnh giấy phép đăng ký Kinh Doanh không chụp từ bản gốc',
  'Mã số thuế trên giấy phép đăng ký Kinh Doanh không rõ',
  'Mã số thuế trên giấy phép đăng ký Kinh Doanh đã được đăng ký ở một công ty khác',
  'Thông tin cá nhân đã được sử dụng để đăng ký Ví',
  'Hộ chiếu chỉ dùng để định danh cho người nước ngoài',
  'Hộ chiếu không còn giá trị sử dụng. Vui lòng cập nhật và gửi duyệt lại.',
  'Hộ chiếu thiếu trang thị thực tại quốc gia cấp thị thực. Vui lòng cập nhật và gửi duyệt lại.',
  'Hình ảnh Hộ chiếu không rõ .Vui lòng cập nhật và gửi duyệt lại.',
];
