export enum GET_LIST_ACOUNTANT_CROSS_CHECK {
  REQUEST = 'GET_LIST_ACOUNTANT_CROSS_CHECK_REQUEST',
  SUCCESS = 'GET_LIST_ACOUNTANT_CROSS_CHECK_SUCCESS',
  FAILURE = 'GET_LIST_ACOUNTANT_CROSS_CHECK_FAILURE',
  DELETE = 'GET_LIST_ACOUNTANT_CROSS_CHECK_DELETE',
}
export enum CREATE_ACOUNTANT_CROSS_CHECK {
  REQUEST = 'CREATE_ACOUNTANT_CROSS_CHECK_REQUEST',
  SUCCESS = 'CREATE_ACOUNTANT_CROSS_CHECK_SUCCESS',
  FAILURE = 'CREATE_ACOUNTANT_CROSS_CHECK_FAILURE',
}
export enum GET_ACOUNTANT_CROSS_CHECK_iTEM {
  REQUEST = 'GET_ACOUNTANT_CROSS_CHECK_iTEM_REQUEST',
  SUCCESS = 'GET_ACOUNTANT_CROSS_CHECK_iTEM_SUCCESS',
  FAILURE = 'GET_ACOUNTANT_CROSS_CHECK_iTEM_FAILURE',
}
export enum EXPORT_ACOUNTANT_CROSS_CHECK {
  PENDING = 'EXPORT_ACOUNTANT_CROSS_CHECK_PENDING',
  REQUEST = 'EXPORT_ACOUNTANT_CROSS_CHECK_REQUEST',
  SUCCESS = 'EXPORT_ACOUNTANT_CROSS_CHECK_SUCCESS',
  FAILURE = 'EXPORT_ACOUNTANT_CROSS_CHECK_FAILURE',
}
export enum UPDATE_STATE_CROSS_CHECK {
  REQUEST = 'UPDATE_STATE_CROSS_CHECK_REQUEST',
  SUCCESS = 'UPDATE_STATE_CROSS_CHECK_SUCCESS',
  FAILURE = 'UPDATE_STATE_CROSS_CHECK_FAILURE',
}
export enum UPDATE_STATE_FINAL_CROSS_CHECK {
  REQUEST = 'UPDATE_STATE_FINAL_CROSS_CHECK_REQUEST',
  SUCCESS = 'UPDATE_STATE_FINAL_CROSS_CHECK_SUCCESS',
  FAILURE = 'UPDATE_STATE_FINAL_CROSS_CHECK_FAILURE',
}
export enum APPROVE_CROSS_CHECK {
  REQUEST = 'APPROVE_CROSS_CHECK_REQUEST',
  SUCCESS = 'APPROVE_CROSS_CHECK_SUCCESS',
  FAILURE = 'APPROVE_CROSS_CHECK_FAILURE',
}

export enum BO_REJECT_CROSS_CHECK {
  REQUEST = 'BO_REJECT_CROSS_CHECK_REQUEST',
  SUCCESS = 'BO_REJECT_CROSS_CHECK_SUCCESS',
  FAILURE = 'BO_REJECT_CROSS_CHECK_FAILURE',
}
export enum BO_CANCEL_CROSS_CHECK {
  REQUEST = 'BO_CANCEL_CROSS_CHECK_REQUEST',
  SUCCESS = 'BO_CANCEL_CROSS_CHECK_SUCCESS',
  FAILURE = 'BO_CANCEL_CROSS_CHECK_FAILURE',
}
export enum BO_PAUSE_CROSS_CHECK {
  REQUEST = 'BO_PAUSE_CROSS_CHECK_REQUEST',
  SUCCESS = 'BO_PAUSE_CROSS_CHECK_SUCCESS',
  FAILURE = 'BO_PAUSE_CROSS_CHECK_FAILURE',
}
export enum BO_TRANSFER_CROSS_CHECK {
  REQUEST = 'BO_TRANSFER_CROSS_CHECK_REQUEST',
  SUCCESS = 'BO_TRANSFER_CROSS_CHECK_SUCCESS',
  FAILURE = 'BO_TRANSFER_CROSS_CHECK_FAILURE',
}
export enum BO_COMPLETE_CROSS_CHECK {
  REQUEST = 'BO_COMPLETE_CROSS_CHECK_REQUEST',
  SUCCESS = 'BO_COMPLETE_CROSS_CHECK_SUCCESS',
  FAILURE = 'BO_COMPLETE_CROSS_CHECK_FAILURE',
}
export enum BO_CONTINUE_PAUSE_CROSS_CHECK {
  REQUEST = 'BO_CONTINUE_PAUSE_CROSS_CHECK_REQUEST',
  SUCCESS = 'BO_CONTINUE_PAUSE_CROSS_CHECK_SUCCESS',
  FAILURE = 'BO_CONTINUE_PAUSE_CROSS_CHECK_FAILURE',
}
export enum EXPORT_SEARCH_ACCOUNTANT {
  PENDING = 'EXPORT_SEARCH_ACCOUNTANT_PENDING',
  REQUEST = 'EXPORT_SEARCH_ACCOUNTANT_REQUEST',
  SUCCESS = 'EXPORT_SEARCH_ACCOUNTANT_SUCCESS',
  FAILURE = 'EXPORT_SEARCH_ACCOUNTANT_FAILURE',
}
export enum GET_MERCHANT_REPORT_CROSS_CHECK {
  REQUEST = 'GET_MERCHANT_REPORT_CROSS_CHECK_REQUEST',
  SUCCESS = 'GET_MERCHANT_REPORT_CROSS_CHECK_SUCCESS',
  FAILURE = 'GET_MERCHANT_REPORT_CROSS_CHECK_FAILURE',
}
