export enum SEARCH_ACCOUNT_MERCHANT {
    REQUEST = "SEARCH_ACCOUNT_MERCHANT_REQUEST",
    SUCCESS = "SEARCH_ACCOUNT_MERCHANT_SUCCESS",
    FAILURE = "SEARCH_ACCOUNT_MERCHANT_FAILURE",
}

export const DELETE_ACCOUNT_MC = 'DELETE_ACCOUNT_MC'


export enum UPDATE_ACCOUNT_MERCHANT {
    REQUEST = "UPDATE_ACCOUNT_MERCHANT_REQUEST",
    SUCCESS = "UPDATE_ACCOUNT_MERCHANT_SUCCESS",
    FAILURE = "UPDATE_ACCOUNT_MERCHANT_FAILURE",
}

export enum PASSWORD_TEMPORARY_ACC_MC {
    REQUEST = "PASSWORD_TEMPORARY_ACC_MC_REQUEST",
    SUCCESS = "PASSWORD_TEMPORARY_ACC_MC_SUCCESS",
    FAILURE = "PASSWORD_TEMPORARY_ACC_MC_FAILURE",
}

export enum UNLOCK_ACCOUNT_MC {
    REQUEST = "UNLOCK_ACCOUNT_MC_REQUEST",
    SUCCESS = "UNLOCK_ACCOUNT_MC_SUCCESS",
    FAILURE = "UNLOCK_ACCOUNT_MC_FAILURE",
}

export enum UPDATE_PASSWORD_MC {
    REQUEST = "UPDATE_PASSWORD_MC_REQUEST",
    SUCCESS = "UPDATE_PASSWORD_MC_SUCCESS",
    FAILURE = "UPDATE_PASSWORD_MC_FAILURE",
}

export enum GET_LIST_ROLE_ACCOUNT_MC {
    REQUEST = "GET_LIST_ROLE_ACCOUNT_MC_REQUEST",
    SUCCESS = "GET_LIST_ROLE_ACCOUNT_MC_SUCCESS",
    FAILURE = "GET_LIST_ROLE_ACCOUNT_MC_FAILURE",
}

export enum UPDATE_ACTIVE_ACCOUNT_MC {
    REQUEST = "UPDATE_ACTIVE_ACCOUNT_MC_REQUEST",
    SUCCESS = "UPDATE_ACTIVE_ACCOUNT_MC_SUCCESS",
    FAILURE = "UPDATE_ACTIVE_ACCOUNT_MC_FAILURE",
}

export enum GET_LIST_ACCOUNT_SALE {
    REQUEST = "GET_LIST_ACCOUNT_SALE_REQUEST",
    SUCCESS = "GET_LIST_ACCOUNT_SALE_SUCCESS",
    FAILURE = "GET_LIST_ACCOUNT_SALE_FAILURE",
}

export enum REQUEST_ACTIVE_ACCOUNT {
    REQUEST = "REQUEST_ACTIVE_ACCOUNT_REQUEST",
    SUCCESS = "REQUEST_ACTIVE_ACCOUNT_SUCCESS",
    FAILURE = "REQUEST_ACTIVE_ACCOUNT_FAILURE",
}