export enum GET_MERCHANTS_REPORT {
    REQUEST = "GET_MERCHANTS_REPORT_REQUEST",
    SUCCESS = "GET_MERCHANTS_REPORT_SUCCESS",
    FAILURE = "GET_MERCHANTS_REPORT_FAILURE",
}
export enum GET_PAYMENT_LOCATIONS_REPORT {
    REQUEST = "GET_PAYMENT_LOCATIONS_REPORT_REQUEST",
    SUCCESS = "GET_PAYMENT_LOCATIONS_REPORT_SUCCESS",
    FAILURE = "GET_PAYMENT_LOCATIONS_REPORT_FAILURE",
  
}
export enum GET_PAYMENT_METHOD_REPORT {
    REQUEST = "GET_PAYMENT_METHOD_REPORT_REQUEST",
    SUCCESS = "GET_PAYMENT_METHOD_REPORT_SUCCESS",
    FAILURE = "GET_PAYMENT_METHOD_REPORT_FAILURE",
}
export enum  GET_MERCHANT_TYPE_REPORT {
    REQUEST = "GET_MERCHANT_TYPE_REPORT_REQUEST",
    SUCCESS = "GET_MERCHANT_TYPE_REPORT_SUCCESS",
    FAILURE = "GET_MERCHANT_TYPE_REPORT_FAILURE",
}
export enum  GET_TOP_INCOME_MERCHANT {
    REQUEST = "GET_TOP_INCOME_MERCHANT_REQUEST",
    SUCCESS = "GET_TOP_INCOME_MERCHANT_SUCCESS",
    FAILURE = "GET_TOP_INCOME_MERCHANT_FAILURE",
}
