export const CHECK_AUTH = {
    CHECK_AUTH_REQUEST : "CHECK_AUTH_REQUEST",
    CHECK_AUTH_SUCCESS: "CHECK_AUTH_SUCCESS",
    CHECK_AUTH_FAILURE: "CHECK_AUTH_FAILURE",
    CHECK_AUTH_REFRESH: "CHECK_AUTH_REFRESH",
    CHECK_AUTH_SUCCESS_NOT_ACCESSTOKEN : "CHECK_AUTH_SUCCESS_NOT_ACCESSTOKEN"
}
export const GET_ACCOUNT_INFO = {
GET_ACCOUNT_INFO_REQUEST : "GET_ACCOUNT_INFO_REQUEST",
 GET_ACCOUNT_INFO_SUCCESS : "GET_ACCOUNT_INFO_SUCCESS",
 GET_ACCOUNT_INFO_FAILURE : "GET_ACCOUNT_INFO_FAILURE",
 GET_ACCOUNT_INFO_REFRESH : "GET_ACCOUNT_INFO_REFRESH",
}

export const  GET_LIST_ROLE_OF_ALL_USER = {
    GET_LIST_ROLE_OF_ALL_USER_REQUEST: 'GET_LIST_ROLE_OF_ALL_USER_REQUEST',
    GET_LIST_ROLE_OF_ALL_USER_SUCCESS:'GET_LIST_ROLE_OF_ALL_USER_SUCCESS',
    GET_LIST_ROLE_OF_ALL_USER_FAILURE:'GET_LIST_ROLE_OF_ALL_USER_FAILURE'
}
export const LIST_ROLE_OF_ALL_USER = {
    SET_LIST_ROLE_OF_ALL_USER: 'SET_LIST_ROLE_OF_ALL_USER',
  GET_LIST_SCOPE_OF_ALL_USER: 'GET_LIST_SCOPE_OF_ALL_USER',
  SET_LIST_SCOPE_OF_ALL_USER: 'SET_LIST_SCOPE_OF_ALL_USER',
}
  
export enum SHOW_MODAL_CHANGE_PASSWORD {
    SHOW = "SHOW_MODAL_CHANGE_PASSWORD_SHOW",
    ClOSE = "SHOW_MODAL_CHANGE_PASSWORD_CLOSE",
}
export enum UPDATE_PASSWORD_AUTH {
    REQUEST = "UPDATE_PASSWORD_AUTH_REQUEST",
    SUCCESS = "UPDATE_PASSWORD_AUTH_SUCCESS",
    FAILURE = "UPDATE_PASSWORD_AUTH_FAILURE",
  }
  