

export enum UPDATE_TICKET {
  REQUEST = "UPDATE_TICKET_REQUEST",
  SUCCESS = "UPDATE_TICKET_SUCCESS",
  FAILURE = "UPDATE_TICKET_FAILURE",
}
export enum ADD_TICKET {
    REQUEST = "ADD_TICKET_REQUEST",
    SUCCESS = "ADD_TICKET_SUCCESS",
    FAILURE = "ADD_TICKET_FAILURE",
  }

  export enum GET_SUPPORT_STAFF {
    REQUEST = "GET_SUPPORT_STAFF_REQUEST",
    SUCCESS = "GET_SUPPORT_STAFF_SUCCESS",
    FAILURE = "GET_SUPPORT_STAFF_FAILURE",
  }

  export enum GET_FILTER_VALUE_CUSTOMER_SUPPORT {
    REQUEST = "GET_FILTER_VALUE_CUSTOMER_SUPPORT_REQUEST",
    SUCCESS = "GET_FILTER_VALUE_CUSTOMER_SUPPORT_SUCCESS",
    FAILURE = "GET_FILTER_VALUE_CUSTOMER_SUPPORT_FAILURE",
  }

  export enum GET_LOG_CUSTOMER_SUPPORT {
    REQUEST = "GET_LOG_CUSTOMER_SUPPORT_REQUEST",
    SUCCESS = "GET_LOG_CUSTOMER_SUPPORT_SUCCESS",
    FAILURE = "GET_LOG_CUSTOMER_SUPPORT_FAILURE",
  }
  export enum SEND_EMAIL_CUSTOMER_SUPPORT {
    REQUEST = "SEND_EMAIL_CUSTOMER_SUPPORT_REQUEST",
    SUCCESS = "SEND_EMAIL_CUSTOMER_SUPPORT_SUCCESS",
    FAILURE = "SEND_EMAIL_CUSTOMER_SUPPORT_FAILURE",
  }
  export enum GET_LIST_CUSTOMER_SUPPORT {
    REQUEST = "GET_LIST_CUSTOMER_SUPPORT_REQUEST",
    SUCCESS = "GET_LIST_CUSTOMER_SUPPORT_SUCCESS",
    FAILURE = "GET_LIST_CUSTOMER_SUPPORT_FAILURE",
  }
  export enum GET_DETAIL_CUSTOMER_SUPPORT {
    REQUEST = "GET_DETAIL_CUSTOMER_SUPPORT_REQUEST",
    SUCCESS = "GET_DETAIL_CUSTOMER_SUPPORT_SUCCESS",
    FAILURE = "GET_DETAIL_CUSTOMER_SUPPORT_FAILURE",
  }


  export enum GET_ASSIGN_TARGET {
    REQUEST = "GET_ASSIGN_TARGET_REQUEST",
    SUCCESS = "GET_ASSIGN_TARGET_SUCCESS",
    FAILURE = "GET_ASSIGN_TARGET_FAILURE",
  }
  export enum GET_DATA_DASHBOARD_TICKET {
    REQUEST = "GET_DATA_DASHBOARD_TICKET_REQUEST",
    SUCCESS = "GET_DATA_DASHBOARD_TICKET_SUCCESS",
    FAILURE = "GET_DATA_DASHBOARD_TICKET_FAILURE",
  }
  export enum GET_DETAIL_DATA_DASHBOARD_TICKET {
    REQUEST = "GET_DETAIL_DATA_DASHBOARD_TICKET_REQUEST",
    SUCCESS = "GET_DETAIL_DATA_DASHBOARD_TICKET_SUCCESS",
    FAILURE = "GET_DETAIL_DATA_DASHBOARD_TICKET_FAILURE",
  }
  export enum GET_DATA_RELY_TICKET {
    REQUEST = "GET_DATA_RELY_TICKET_REQUEST",
    SUCCESS = "GET_DATA_RELY_TICKET_SUCCESS",
    FAILURE = "GET_DATA_RELY_TICKET_FAILURE",
  }
  export enum SET_STATE_TICKET {
    REQUEST = "SET_STATE_TICKET_REQUEST",
    SUCCESS = "SET_STATE_TICKET_SUCCESS",
    FAILURE = "SET_STATE_TICKET_FAILURE",
  }
  export enum ADD_RELY_DASHBOARD_TICKET {
    REQUEST = "ADD_RELY_DASHBOARD_TICKET_REQUEST",
    SUCCESS = "ADD_RELY_DASHBOARD_TICKET_SUCCESS",
    FAILURE = "ADD_RELY_DASHBOARD_TICKET_FAILURE",
  }
  
  