export enum DEPOSIT_WITHDRAW {
  REQUEST = 'DEPOSIT_WITHDRAW_REQUEST',
  SUCCESS = 'DEPOSIT_WITHDRAW_SUCCESS',
  FAILURE = 'DEPOSIT_WITHDRAW_FAILURE',
}
export enum DEPOSIT_WITHDRAW_EWALLET {
  REQUEST = ' DEPOSIT_WITHDRAW_EWALLET_REQUEST',
  SUCCESS = ' DEPOSIT_WITHDRAW_EWALLET_SUCCESS',
  FAILURE = ' DEPOSIT_WITHDRAW_EWALLET_FAILURE',
}
export enum GET_LIST_BALANCE_MERCHANT {
  REQUEST = ' GET_LIST_BALANCE_MERCHANT_REQUEST',
  SUCCESS = ' GET_LIST_BALANCE_MERCHANT_SUCCESS',
  FAILURE = ' GET_LIST_BALANCE_MERCHANT_FAILURE',
  DELETE =' GET_LIST_BALANCE_MERCHANT_DELETE'
}
