export enum EMAIL_SMS_PRODUCT {
  REQUEST = 'EMAIL_SMS_PRODUCT_REQUEST',
  SUCCESS = 'EMAIL_SMS_PRODUCT_SUCCESS',
  FAILURE = 'EMAIL_SMS_PRODUCT_FAILURE',
}
export enum EMAIL_SMS_MERCHANT {
  REQUEST = 'EMAIL_SMS_MERCHANT_REQUEST',
  SUCCESS = 'EMAIL_SMS_MERCHANT_SUCCESS',
  FAILURE = 'EMAIL_SMS_MERCHANT_FAILURE',
}
export enum EMAIL_SMS_HISTORY {
  REQUEST = 'EMAIL_SMS_HISTORY_REQUEST',
  SUCCESS = 'EMAIL_SMS_HISTORY_SUCCESS',
  FAILURE = 'EMAIL_SMS_HISTORY_FAILURE',
}
export enum CREATE_EMAIL_SMS_PRODUCT {
  REQUEST = 'CREATE_EMAIL_SMS_PRODUCT_REQUEST',
  SUCCESS = 'CREATE_EMAIL_SMS_PRODUCT_SUCCESS',
  FAILURE = 'CREATE_EMAIL_SMS_PRODUCT_FAILURE',
}
export enum UPDATE_EMAIL_SMS_PRODUCT {
  REQUEST = 'UPDATE_EMAIL_SMS_PRODUCT_REQUEST',
  SUCCESS = 'UPDATE_EMAIL_SMS_PRODUCT_SUCCESS',
  FAILURE = 'UPDATE_EMAIL_SMS_PRODUCT_FAILURE',
}