export enum REPORT_CHECK_SUM {
  REQUEST = 'REPORT_CHECK_SUM_REQUEST',
  SUCCESS = 'REPORT_CHECK_SUM_SUCCESS',
  FAILURE = 'REPORT_CHECK_SUM_FAILURE',
}

export enum GET_REPORT_USER {
  REQUEST = 'GET_REPORT_USER_REQUEST',
  SUCCESS = 'GET_REPORT_USER_SUCCESS',
  FAILURE = 'GET_REPORT_USER_FAILURE',
}

export enum GET_STATISTIC_REPORT_USER {
  REQUEST = 'GET_STATISTIC_REPORT_USER_REQUEST',
}


export enum EXPORT_FILE_REPORT_USER {
  REQUEST = 'EXPORT_FILE_REPORT_USER_REQUEST',
  SUCCESS = 'EXPORT_FILE_REPORT_USER_SUCCESS',
  FAILURE = 'EXPORT_FILE_REPORT_USER_FAILURE',
  PENDING = 'EXPORT_FILE_REPORT_USER_PENDING',
}