
export enum GET_LIST_E_WALLET_HISTORY_LOGIN {
    REQUEST = 'GET_LIST_E_WALLET_HISTORY_LOGIN_REQUEST',
    SUCCESS = 'GET_LIST_E_WALLET_HISTORY_LOGIN_SUCCESS',
    FAILURE = 'GET_LIST_E_WALLET_HISTORY_LOGIN_FAILURE',
}

