export enum GET_LIST_PAYME_TRANSFER_HISTORY {
  REQUEST = 'GET_LIST_PAYME_TRANSFER_HISTORY_REQUEST',
  SUCCESS = 'GET_LIST_PAYME_TRANSFER_HISTORY_SUCCESS',
  FAILURE = 'GET_LIST_PAYME_TRANSFER_HISTORY_FAILURE',
}

export enum GET_LIST_PAYME_TRANSFER_LOG {
  REQUEST = 'GET_LIST_PAYME_TRANSFER_LOG_REQUEST',
  SUCCESS = 'GET_LIST_PAYME_TRANSFER_LOG_SUCCESS',
  FAILURE = 'GET_LIST_PAYME_TRANSFER_LOG_FAILURE',
}

export enum GET_DETAIL_PAYME_TRANSFER {
  REQUEST = 'GET_DETAIL_PAYME_TRANSFER_REQUEST',
  SUCCESS = 'GET_DETAIL_PAYME_TRANSFER_SUCCESS',
  FAILURE = 'GET_DETAIL_PAYME_TRANSFER_FAILURE',
}

export enum TRANSFER_WALLET_PAYME {
  REQUEST = 'TRANSFER_WALLET_PAYME_REQUEST',
  SUCCESS = 'TRANSFER_WALLET_PAYME_SUCCESS',
  FAILURE = 'TRANSFER_WALLET_PAYME_FAILURE',
}

export enum CONFIRM_TRANSFER_WALLET_PAYME {
  REQUEST = 'CONFIRM_TRANSFER_WALLET_PAYME_REQUEST',
  SUCCESS = 'CONFIRM_TRANSFER_WALLET_PAYME_SUCCESS',
  FAILURE = 'CONFIRM_TRANSFER_WALLET_PAYME_FAILURE',
}

export enum CREATE_COMMAND_TRANSFER_WALLET_PAYME {
  REQUEST = 'CREATE_COMMAND_TRANSFER_WALLET_PAYME_REQUEST',
  SUCCESS = 'CREATE_COMMAND_TRANSFER_WALLET_PAYME_SUCCESS',
  FAILURE = 'CREATE_COMMAND_TRANSFER_WALLET_PAYME_FAILURE',
}