export enum GET_LIST_EWALLET_BANK_REPORT_MERCHANT_TT23 {
  REQUEST = 'GET_LIST_EWALLET_BANK_REPORT_MERCHANT_TT23_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_BANK_REPORT_MERCHANT_TT23_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_BANK_REPORT_MERCHANT_TT23_FAILURE',
}

export enum GET_LIST_EWALLET_BANK_REPORT_EWALLET_TT23 {
  REQUEST = 'GET_LIST_EWALLET_BANK_REPORT_EWALLET_TT23_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_BANK_REPORT_EWALLET_TT23_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_BANK_REPORT_EWALLET_TT23_FAILURE',
}

export enum GET_LIST_EWALLET_BANK_REPORT_DETAIL_EWALLET_TT23 {
  REQUEST = 'GET_LIST_EWALLET_BANK_REPORT_DETAIL_EWALLET_TT23_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_BANK_REPORT_DETAIL_EWALLET_TT23_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_BANK_REPORT_DETAIL_EWALLET_TT23_FAILURE',
}

export enum GET_LIST_EWALLET_BANK_REPORT_BILL_TT23 {
  REQUEST = 'GET_LIST_EWALLET_BANK_REPORT_BILL_TT23_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_BANK_REPORT_BILL_TT23_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_BANK_REPORT_BILL_TT23_FAILURE',
}
