export enum GET_LIST_EWALLET_ISEC_REPORT {
  REQUEST = 'GET_LIST_EWALLET_ISEC_REPORT_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_ISEC_REPORT_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_ISEC_REPORT_FAILURE',
}

export enum GET_LIST_EWALLET_ISEC_CODE_REPORT {
  REQUEST = 'GET_LIST_EWALLET_ISEC_CODE_REPORT_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_ISEC_CODE_REPORT_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_ISEC_CODE_REPORT_FAILURE',
}

export enum GET_LIST_EWALLET_ISEC_REPORT_TRANSACTION {
  REQUEST = 'GET_LIST_EWALLET_ISEC_REPORT_TRANSACTION_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_ISEC_REPORT_TRANSACTION_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_ISEC_REPORT_TRANSACTION_FAILURE',
}

export enum GET_LIST_EWALLET_ISEC_REPORT_BY_ACCOUNT {
  REQUEST = 'GET_LIST_EWALLET_ISEC_REPORT_BY_ACCOUNT_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_ISEC_REPORT_BY_ACCOUNT_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_ISEC_REPORT_BY_ACCOUNT_FAILURE',
}
