
export enum GET_LIST_E_WALLET_TRANSACTION {
  REQUEST = 'GET_LIST_E_WALLET_TRANSACTION_REQUEST',
  SUCCESS = 'GET_LIST_E_WALLET_TRANSACTION_SUCCESS',
  FAILURE = 'GET_LIST_E_WALLET_TRANSACTION_FAILURE',
}

export enum GET_SERVICE_SEARCH_TRANSACTION {
  REQUEST = 'GET_SERVICE_SEARCH_TRANSACTION_REQUEST',
  SUCCESS = 'GET_SERVICE_SEARCH_TRANSACTION_SUCCESS',
  FAILURE = 'GET_SERVICE_SEARCH_TRANSACTION_FAILURE',
}

export enum REFUND_E_WALLET_TRANSACTION {
  REQUEST = 'REFUND_E_WALLET_TRANSACTION_REQUEST',
  SUCCESS = 'REFUND_E_WALLET_TRANSACTION_SUCCESS',
  FAILURE = 'REFUND_E_WALLET_TRANSACTION_FAILURE',
}

export enum EXPORT_E_WALLET_TRANSACTION {
  REQUEST = 'EXPORT_E_WALLET_TRANSACTION_REQUEST',
  SUCCESS = 'EXPORT_E_WALLET_TRANSACTION_SUCCESS',
  FAILURE = 'EXPORT_E_WALLET_TRANSACTION_FAILURE',
  PENDING = 'EXPORT_E_WALLET_TRANSACTION_PENDING',
}

export enum GET_TOP_TRANSACTION_BY_DATE {
    REQUEST = 'GET_TOP_TRANSACTION_BY_DATE_REQUEST',
    SUCCESS = 'GET_TOP_TRANSACTION_BY_DATE_SUCCESS',
  FAILURE = 'GET_TOP_TRANSACTION_BY_DATE_FAILURE',
  DELETE = 'GET_TOP_TRANSACTION_BY_DATE_DELETE',
  }
  
  export enum GET_TOP_TRANSACTION_BY_ACCOUNT {
    REQUEST = 'GET_TOP_TRANSACTION_BY_ACCOUNT_REQUEST',
    SUCCESS = 'GET_TOP_TRANSACTION_BY_ACCOUNT_SUCCESS',
    FAILURE = 'GET_TOP_TRANSACTION_BY_ACCOUNT_FAILURE',
  }
  export enum GET_TOP_TRANSACTION_BY_ACCOUNT_AMOUNT {
    REQUEST = 'GET_TOP_TRANSACTION_BY_ACCOUNT_AMOUNT_REQUEST',
    SUCCESS = 'GET_TOP_TRANSACTION_BY_ACCOUNT_AMOUNT_SUCCESS',
    FAILURE = 'GET_TOP_TRANSACTION_BY_ACCOUNT_AMOUNT_FAILURE',
  }
  
  export enum GET_TOP_ACCOUNT_LOGIN {
    REQUEST = 'GET_TOP_ACCOUNT_LOGIN_REQUEST',
    SUCCESS = 'GET_TOP_ACCOUNT_LOGIN_SUCCESS',
    FAILURE = 'GET_TOP_ACCOUNT_LOGIN_FAILURE',
  }
export enum GET_LIST_E_WALLET_TRANSACTION_SUPPLIER {
  REQUEST = 'GET_LIST_E_WALLET_TRANSACTION_SUPPLIER_REQUEST',
  SUCCESS = 'GET_LIST_E_WALLET_TRANSACTION_SUPPLIER_SUCCESS',
  FAILURE = 'GET_LIST_E_WALLET_TRANSACTION_SUPPLIER_FAILURE',
}

export enum GET_LIST_E_WALLET_DETAILS {
  REQUEST = 'GET_LIST_E_WALLET_DETAILS_REQUEST',
}
