export enum GET_EWALLET_SERVICE_REPORT_BILL {
  REQUEST = 'GET_EWALLET_SERVICE_REPORT_BILL_REQUEST',
  SUCCESS = 'GET_EWALLET_SERVICE_REPORT_BILL_SUCCESS',
  FAILURE = 'GET_EWALLET_SERVICE_REPORT_BILL_FAILURE',
}
export enum GET_BANK_REPORT {
  REQUEST = 'GET_BANK_REPORT_REQUEST',
  SUCCESS = 'GET_BANK_REPORT_SUCCESS',
  FAILURE = 'GET_BANK_REPORT_FAILURE',
}
export enum GET_EWALLET_GATE_REPORT {
  REQUEST = 'GET_EWALLET_GATE_REPORT_REQUEST',
  SUCCESS = 'GET_EWALLET_GATE_REPORT_SUCCESS',
  FAILURE = 'GET_EWALLET_GATE_REPORT_FAILURE',
}

export enum GET_EWALLET_HISTORY_REPORT {
  REQUEST = 'GET_EWALLET_HISTORY_REPORT_REQUEST',
  SUCCESS = 'GET_EWALLET_HISTORY_REPORT_SUCCESS',
  FAILURE = 'GET_EWALLET_HISTORY_REPORT_FAILURE',
}

export enum GET_EWALLET_SSCC_REPORT {
  REQUEST = 'GET_EWALLET_SSCC_REPORT_REQUEST',
  SUCCESS = 'GET_EWALLET_SSCC_REPORT_SUCCESS',
  FAILURE = 'GET_EWALLET_SSCC_REPORT_FAILURE',
}

export enum EXPORT_PARTNER_SERVICE {
  REQUEST = 'EXPORT_PARTNER_SERVICE_REQUEST',
  SUCCESS = 'EXPORT_PARTNER_SERVICE_SUCCESS',
  FAILURE = 'EXPORT_PARTNER_SERVICE_FAILURE',
  PENDING = 'EXPORT_PARTNER_SERVICE_PENDING'
}