export enum GET_LIST_EWALLET_WORD_FILLTER {
    REQUEST = 'GET_LIST_EWALLET_WORD_FILLTER_REQUEST',
    SUCCESS = 'GET_LIST_EWALLET_WORD_FILLTER_SUCCESS',
    FAILURE = 'GET_LIST_EWALLET_WORD_FILLTER_FAILURE',
}
export enum CREATE_EWALLET_WORD_FILLTER {
    REQUEST = 'CREATE_EWALLET_WORD_FILLTER_REQUEST',
    SUCCESS = 'CREATE_EWALLET_WORD_FILLTER_SUCCESS',
    FAILURE = 'CREATE_EWALLET_WORD_FILLTER_FAILURE',
}
export enum UPDATE_EWALLET_WORD_FILLTER {
    REQUEST = 'UPDATE_EWALLET_WORD_FILLTER_REQUEST',
    SUCCESS = 'UPDATE_EWALLET_WORD_FILLTER_SUCCESS',
    FAILURE = 'UPDATE_EWALLET_WORD_FILLTER_FAILURE',
  }