
export enum GET_LIST_CONNECTED_USER {
  REQUEST = 'GET_LIST_CONNECTED_USER_REQUEST',
  SUCCESS = 'GET_LIST_CONNECTED_USER_SUCCESS',
  FAILURE = 'GET_LIST_CONNECTED_USER_FAILURE',
}

export enum UNLINK_CONNECTED_USER {
  REQUEST = 'UNLINK_CONNECTED_USER_REQUEST',
  SUCCESS = 'UNLINK_CONNECTED_USER_SUCCESS',
  FAILURE = 'UNLINK_CONNECTED_USER_FAILURE',
}
