export enum GET_LIST_EWALLET_BANK_TRANSACTION {
  REQUEST = 'GET_LIST_EWALLET_BANK_TRANSACTION_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_BANK_TRANSACTION_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_BANK_TRANSACTION_FAILURE',
}

export enum GET_LIST_EWALLET_BANK_TRANSACTION_REPORT {
  REQUEST = 'GET_LIST_EWALLET_BANK_TRANSACTION_REPORT_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_BANK_TRANSACTION_REPORT_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_BANK_TRANSACTION_REPORT_FAILURE',
}

export enum EXPORT_EWALLET_BANK_TRANSACTION {
  REQUEST = 'EXPORT_EWALLET_BANK_TRANSACTION_REQUEST',
  SUCCESS = 'EXPORT_EWALLET_BANK_TRANSACTION_SUCCESS',
  FAILURE = 'EXPORT_EWALLET_BANK_TRANSACTION_FAILURE',
}
