export enum GET_LIST_EWALLET_SOCIAL_PAY {
  REQUEST = 'GET_LIST_EWALLET_SOCIAL_PAY_REQUEST',
  SUCCESS = 'GET_LIST_EWALLET_SOCIAL_PAY_SUCCESS',
  FAILURE = 'GET_LIST_EWALLET_SOCIAL_PAY_FAILURE',
}

export enum GET_LIST_REPORT_EWALLET_SOCIAL {
  REQUEST = 'GET_LIST_REPORT_EWALLET_SOCIAL_REQUEST',
  SUCCESS = 'GET_LIST_REPORT_EWALLET_SOCIAL_SUCCESS',
  FAILURE = 'GET_LIST_REPORT_EWALLET_SOCIAL_FAILURE',
}
