export enum GET_LIST_TRANSACTION_CENSORSHIP {
  REQUEST = 'GET_LIST_TRANSACTION_CENSORSHIP_REQUEST',
  SUCCESS = 'GET_LIST_TRANSACTION_CENSORSHIP_SUCCESS',
  FAILURE = 'GET_LIST_TRANSACTION_CENSORSHIP_FAILURE',
}