export enum RESEND_EMAIL_MERCHANT {
    REQUEST = 'RESEND_EMAIL_MERCHANT_REQUEST',
    SUCCESS = 'RESEND_EMAIL_MERCHANT_SUCCESS',
    FAILURE = 'RESEND_EMAIL_MERCHANT_FAILURE',
  }
  export enum EXPORT_EMAIL_MERCHANT {
    REQUEST = 'EXPORT_EMAIL_MERCHANT_REQUEST',
    SUCCESS = 'EXPORT_EMAIL_MERCHANT_SUCCESS',
    FAILURE = 'EXPORT_EMAIL_MERCHANT_FAILURE',
    PENDING ='EXPORT_EMAIL_MERCHANT_PENDING'
  }
  export enum GET_EMAIL_INFORMATION_MERCHANT {
    REQUEST = 'GET_EMAIL_INFORMATION_MERCHANT_REQUEST',
    SUCCESS = 'GET_EMAIL_INFORMATION_MERCHANT_SUCCESS',
    FAILURE = 'GET_EMAIL_INFORMATION_MERCHANT_FAILURE',
  }