
export enum GET_LIST_AVATAR_IMAGE {
    REQUEST = 'GET_LIST_AVATAR_IMAGE_REQUEST',
    SUCCESS = 'GET_LIST_AVATAR_IMAGE_SUCCESS',
    FAILURE = 'GET_LIST_AVATAR_IMAGE_FAILURE',
}

export enum REFUSE_AVATAR_IMAGE {
    REQUEST = 'REFUSE_AVATAR_IMAGE_REQUEST',
    SUCCESS = 'REFUSE_AVATAR_IMAGE_SUCCESS',
    FAILURE = 'REFUSE_AVATAR_IMAGE_FAILURE',
}

export enum GET_LIST_ALIASNAME {
    REQUEST = 'GET_LIST_ALIASNAME_REQUEST',
    SUCCESS = 'GET_LIST_ALIASNAME_SUCCESS',
    FAILURE = 'GET_LIST_ALIASNAME_FAILURE',
}

export enum UPDATE_ALIASNAME {
    REQUEST = 'UPDATE_ALIASNAME_REQUEST',
    SUCCESS = 'UPDATE_ALIASNAME_SUCCESS',
    FAILURE = 'UPDATE_ALIASNAME_FAILURE',
}

export enum REFUSE_ALIASNAME {
    REQUEST = 'REFUSE_ALIASNAME_REQUEST',
    SUCCESS = 'REFUSE_ALIASNAME_SUCCESS',
    FAILURE = 'REFUSE_ALIASNAME_FAILURE',
}