export enum GET_LINKED_BANKS {
  REQUEST = 'GET_LINKED_BANKS_REQUEST',
  SUCCESS = 'GET_LINKED_BANKS_SUCCESS',
  FAILURE = 'GET_LINKED_BANKS_FAILURE',
}

export enum UNLINK_BANK {
  REQUEST = 'UNLINK_BANK_REQUEST',
  SUCCESS = 'UNLINK_BANK_SUCCESS',
  FAILURE = 'UNLINK_BANK_FAILURE',
}
