export enum GET_WALLET_LOAN_PACKAGE {
  REQUEST = 'GET_WALLET_LOAN_PACKAGE_REQUEST',
  SUCCESS = 'GET_WALLET_LOAN_PACKAGE_SUCCESS',
  FAILURE = 'GET_WALLET_LOAN_PACKAGE_FAILURE',
}

export enum UPDATE_WALLET_LOAN_PACKAGE {
  REQUEST = 'UPDATE_WALLET_LOAN_PACKAGE_REQUEST',
  SUCCESS = 'UPDATE_WALLET_LOAN_PACKAGE_SUCCESS',
  FAILURE = 'UPDATE_WALLET_LOAN_PACKAGE_FAILURE',
}
