export enum GET_LOCKED_CARDS {
  REQUEST = "GET_LOCKED_CARDS_REQUEST",
  SUCCESS = "GET_LOCKED_CARDS_SUCCESS",
  FAILURE = "GET_LOCKED_CARDS_FAILURE",
}

export enum UPDATE_LOCKED_CARD {
  REQUEST = "UPDATE_LOCKED_CARD_REQUEST",
  SUCCESS = "UPDATE_LOCKED_CARD_SUCCESS",
  FAILURE = "UPDATE_LOCKED_CARD_FAILURE",
}

export enum LOCKED_CARD {
  REQUEST = "LOCKED_CARD_REQUEST",
  SUCCESS = "LOCKED_CARD_SUCCESS",
  FAILURE = "LOCKED_CARD_FAILURE",
}