export enum LOGIN_HISTORY_CTT {
  REQUEST = 'LOGIN_HISTORY_CTT_REQUEST',
  SUCCESS = 'LOGIN_HISTORY_CTT_SUCCESS',
  FAILURE = 'LOGIN_HISTORY_CTT_FAILURE',
}

export enum EXPORT_LOGIN_HISTORY_CTT {
  REQUEST = 'EXPORT_LOGIN_HISTORY_CTT_REQUEST',
  SUCCESS = 'EXPORT_LOGIN_HISTORY_CTT_SUCCESS',
  FAILURE = 'EXPORT_LOGIN_HISTORY_CTT_FAILURE',
}
