export enum SEARCH_ACCOUNTS_WALLET_PAYME {
  REQUEST = 'SEARCH_ACCOUNTS_WALLET_PAYME_REQUEST',
  SUCCESS = 'SEARCH_ACCOUNTS_WALLET_PAYME_SUCCESS',
  FAILURE = 'SEARCH_ACCOUNTS_WALLET_PAYME_FAILURE',
}

export enum ADD_ACCOUNTS_WALLET_PAYME {
  REQUEST = 'ADD_ACCOUNTS_WALLET_PAYME_REQUEST',
  SUCCESS = 'ADD_ACCOUNTS_WALLET_PAYME_SUCCESS',
  FAILURE = 'ADD_ACCOUNTS_WALLET_PAYME_FAILURE',
}

export enum UPDATE_ACCOUNTS_WALLET_PAYME {
  REQUEST = 'UPDATE_ACCOUNTS_WALLET_PAYME_REQUEST',
  SUCCESS = 'UPDATE_ACCOUNTS_WALLET_PAYME_SUCCESS',
  FAILURE = 'UPDATE_ACCOUNTS_WALLET_PAYME_FAILURE',
}

export enum DELETE_ACCOUNTS_WALLET_PAYME {
  REQUEST = 'DELETE_ACCOUNTS_WALLET_PAYME_REQUEST',
  SUCCESS = 'DELETE_ACCOUNTS_WALLET_PAYME_SUCCESS',
  FAILURE = 'DELETE_ACCOUNTS_WALLET_PAYME_FAILURE',
}

export enum GET_LIST_COMPANY {
  REQUEST = 'GET_LIST_COMPANY_REQUEST',
  SUCCESS = 'GET_LIST_COMPANY_SUCCESS',
  FAILURE = 'GET_LIST_COMPANY_FAILURE',
}
