export enum GET_LIST_BANK {
  REQUEST = 'GET_LIST_BANK_REQUEST',
  SUCCESS = 'GET_LIST_BANK_SUCCESS',
  FAILURE = 'GET_LIST_BANK_FAILURE',
}

export enum GET_LIST_ACCOUNT_BANK {
  REQUEST = 'GET_LIST_ACCOUNT_BANK_REQUEST',
  SUCCESS = 'GET_LIST_ACCOUNT_BANK_SUCCESS',
  FAILURE = 'GET_LIST_ACCOUNT_BANK_FAILURE',
}

export enum GET_LIST_MANUAL_BANK {
  REQUEST = 'GET_LIST_MANUAL_BANK_REQUEST',
  SUCCESS = 'GET_LIST_MANUAL_BANK_SUCCESS',
  FAILURE = 'GET_LIST_MANUAL_BANK_FAILURE',
}

export enum GET_LIST_MANUAL_BANK_DEPOSIT {
  REQUEST = 'GET_LIST_MANUAL_BANK_DEPOSIT_REQUEST',
  SUCCESS = 'GET_LIST_MANUAL_BANK_DEPOSIT_SUCCESS',
  FAILURE = 'GET_LIST_MANUAL_BANK_DEPOSIT_FAILURE',
}

export enum CREATE_BANK_TRANSFER_TRANSACTION {
  REQUEST = 'CREATE_BANK_TRANSFER_TRANSACTION_REQUEST',
  SUCCESS = 'CREATE_BANK_TRANSFER_TRANSACTION_SUCCESS',
  FAILURE = 'CREATE_BANK_TRANSFER_TRANSACTION_FAILURE',
}

export enum UPDATE_BANK_TRANSFER_TRANSACTION {
  REQUEST = 'UPDATE_BANK_TRANSFER_TRANSACTION_REQUEST',
  SUCCESS = 'UPDATE_BANK_TRANSFER_TRANSACTION_SUCCESS',
  FAILURE = 'UPDATE_BANK_TRANSFER_TRANSACTION_FAILURE',
}

export enum CREATE_DEPOSIT_BANK {
  REQUEST = 'CREATE_DEPOSIT_BANK_REQUEST',
  SUCCESS = 'CREATE_DEPOSIT_BANK_SUCCESS',
  FAILURE = 'CREATE_DEPOSIT_BANK_FAILURE',
}

export enum UPDATE_BANK_DEPOSIT {
  REQUEST = 'UPDATE_BANK_DEPOSIT_REQUEST',
  SUCCESS = 'UPDATE_BANK_DEPOSIT_SUCCESS',
  FAILURE = 'UPDATE_BANK_DEPOSIT_FAILURE',
}

export enum UPDATE_BANK_PAYMENT {
  REQUEST = 'UPDATE_BANK_PAYMENT_REQUEST',
  SUCCESS = 'UPDATE_BANK_PAYMENT_SUCCESS',
  FAILURE = 'UPDATE_BANK_PAYMENT_FAILURE',
}