import { LOADING_DRAWER } from './transactionType';
export enum SEARCH_MERCHANT {
  REQUEST = 'SEARCH_MERCHANT_REQUEST',
  SUCCESS = 'SEARCH_MERCHANT_SUCCESS',
  FAILURE = 'SEARCH_MERCHANT_FAILURE',
}

export enum GET_PROFILE_MERCHANT {
  REQUEST = 'GET_PROFILE_MERCHANT_REQUEST',
  SUCCESS = 'GET_PROFILE_MERCHANT_SUCCESS',
  FAILURE = 'GET_PROFILE_MERCHANT_FAILURE',
  RESET = 'GET_PROFILE_MERCHANT_RESET',
}

export enum SEARCH_APPROVAL_MERCHANT {
  REQUEST = 'SEARCH_APPROVAL_MERCHANT_REQUEST',
  SUCCESS = 'SEARCH_APPROVAL_MERCHANT_SUCCESS',
  FAILURE = 'SEARCH_APPROVAL_MERCHANT_FAILURE',
}

export enum UPDATE_INFO_MERCHANT {
  REQUEST = 'UPDATE_INFO_MERCHANT_REQUEST',
  SUCCESS = 'UPDATE_INFO_MERCHANT_SUCCESS',
  FAILURE = 'UPDATE_INFO_MERCHANT_FAILURE',
}

export enum GET_MERCHANT_FEE_CONFIG {
  REQUEST = 'GET_MERCHANT_FEE_CONFIG_REQUEST',
  SUCCESS = 'GET_MERCHANT_FEE_CONFIG_SUCCESS',
  FAILURE = 'GET_MERCHANT_FEE_CONFIG_FAILURE',
}

export enum GET_DEFAULT_MERCHANT_FEE_CONFIG {
  REQUEST = 'GET_DEFAULT_MERCHANT_FEE_CONFIG_REQUEST',
  SUCCESS = 'GET_DEFAULT_MERCHANT_FEE_CONFIG_SUCCESS',
  FAILURE = 'GET_DEFAULT_MERCHANT_FEE_CONFIG_FAILURE',
}

export const UPDATE_METHOD_CHECKED = 'UPDATE_METHOD_CHECKED';

export enum UPDATE_IMAGE_MERCHANT {
  REQUEST = 'UPDATE_IMAGE_MERCHANT_REQUEST',
  SUCCESS = 'UPDATE_IMAGE_MERCHANT_SUCCESS',
  FAILURE = 'UPDATE_IMAGE_MERCHANT_FAILURE',
}

export enum UPDATE_CONFIG_FEE_MERCHANT {
  REQUEST = 'UPDATE_CONFIG_FEE_MERCHANT_REQUEST',
  SUCCESS = 'UPDATE_CONFIG_FEE_MERCHANT_SUCCESS',
  FAILURE = 'UPDATE_CONFIG_FEE_MERCHANT_FAILURE',
}

export enum APPROVING_MERCHANT {
  REQUEST = 'APPROVING_MERCHANT_REQUEST',
  SUCCESS = 'APPROVING_MERCHANT_SUCCESS',
  FAILURE = 'APPROVING_MERCHANT_FAILURE',
}

export enum REJECT_MERCHANT {
  REQUEST = 'REJECT_MERCHANT_REQUEST',
  SUCCESS = 'REJECT_MERCHANT_SUCCESS',
  FAILURE = 'REJECT_MERCHANT_FAILURE',
}

export enum CHANGE_PASSWORD_MERCHANT {
  REQUEST = 'CHANGE_PASSWORD_MERCHANT_REQUEST',
  SUCCESS = 'CHANGE_PASSWORD_MERCHANT_SUCCESS',
  FAILURE = 'CHANGE_PASSWORD_MERCHANT_FAILURE',
}

export enum UPDATE_ACTIVE_MERCHANT {
  REQUEST = 'UPDATE_ACTIVE_MERCHANT_REQUEST',
  SUCCESS = 'UPDATE_ACTIVE_MERCHANT_SUCCESS',
  FAILURE = 'UPDATE_ACTIVE_MERCHANT_FAILURE',
}

export enum UPDATE_ACTIVE_ACCOUNT_MERCHANT {
  REQUEST = 'UPDATE_ACTIVE_ACCOUNT_MERCHANT_REQUEST',
  SUCCESS = 'UPDATE_ACTIVE_ACCOUNT_MERCHANT_SUCCESS',
  FAILURE = 'UPDATE_ACTIVE_ACCOUNT_MERCHANT_FAILURE',
}

export enum GET_LIST_DELEGATE_MC {
  REQUEST = 'GET_LIST_DELEGATE_MC_REQUEST',
  SUCCESS = 'GET_LIST_DELEGATE_MC_SUCCESS',
  FAILURE = 'GET_LIST_DELEGATE_MC_FAILURE',
}

export enum ADD_DELEGATE_MERCHANT {
  REQUEST = 'ADD_DELEGATE_MERCHANT_REQUEST',
  SUCCESS = 'ADD_DELEGATE_MERCHANT_SUCCESS',
  FAILURE = 'ADD_DELEGATE_MERCHANT_FAILURE',
}
export enum SEND_CONTRACT_MERCHANT {
  REQUEST = 'SEND_CONTRACT_MERCHANT_REQUEST',
  SUCCESS = 'SEND_CONTRACT_MERCHANT_SUCCESS',
  FAILURE = 'SEND_CONTRACT_MERCHANT_FAILURE',
  LOADING = 'SEND_CONTRACT_MERCHANT_LOADING',
}

// Create merchant
export enum CREATE_ACCOUNT_MERCHANT {
  REQUEST = 'CREATE_ACCOUNT_MERCHANT_REQUEST',
  SUCCESS = 'CREATE_ACCOUNT_MERCHANT_SUCCESS',
  FAILURE = 'CREATE_ACCOUNT_MERCHANT_FAILURE',
}
export enum APPROVE_PENDING_MERCHANT {
  REQUEST = 'APPROVE_PENDING_MERCHANT_REQUEST',
  SUCCESS = 'APPROVE_PENDING_MERCHANT_SUCESSS',
  FAILURE = 'APPROVE_PENDING_MERCHANT_FAILURE',
}

export enum REJECT_PENDING_MERCHANT {
  REQUEST = 'REJECT_PENDING_MERCHANT_REQUEST',
  SUCCESS = 'REJECT_PENDING_MERCHANT_SUCESSS',
  FAILURE = 'REJECT_PENDING_MERCHANT_FAILURE',
}

export enum GET_BUSSINESS_DETAIL {
  REQUEST = 'GET_BUSSINESS_DETAIL_REQUEST',
}

export enum GET_CHANGED_INFO {
  REQUEST = 'GET_CHANGED_INFO_REQUEST',
  SUCCESS = 'GET_CHANGED_INFO_SUCCESS',
  FAILURE = 'GET_CHANGED_INFO_FAILURE',
}

export enum GET_CHANGED_INFO_WALLET_ACCOUNT {
  REQUEST = 'GET_CHANGED_INFO_WALLET_ACCOUNT_REQUEST',
  SUCCESS = 'GET_CHANGED_INFO_WALLET_ACCOUNT_SUCCESS',
  FAILURE = 'GET_CHANGED_INFO_WALLET_ACCOUNT_FAILURE',
}

export enum GET_MERCHANT_ACTIVE_INFO {
  REQUEST = 'GET_MERCHANT_ACTIVE_INFO_REQUEST',
  SUCCESS = 'GET_MERCHANT_ACTIVE_INFO_SUCCESS',
  FAILURE = 'GET_MERCHANT_ACTIVE_INFO_FAILURE',
}

export enum GET_ACCOUNT_ACTIVE_INFO {
  REQUEST = 'GET_ACCOUNT_ACTIVE_INFO_REQUEST',
  SUCCESS = 'GET_ACCOUNT_ACTIVE_INFO_SUCCESS',
  FAILURE = 'GET_ACCOUNT_ACTIVE_INFO_FAILURE',
}

export enum REQUEST_UPDATE_INFO {
  REQUEST = 'REQUEST_UPDATE_INFO_REQUEST',
}

export enum REQUEST_UPDATE_FEE {
  REQUEST = 'REQUEST_UPDATE_FEE_REQUEST',
}

export enum GET_MERCHANT_LOG {
  REQUEST = 'GET_MERCHANT_LOG_REQUEST',
  SUCCESS = 'GET_MERCHANT_LOG_SUCESSS',
  FAILURE = 'GET_MERCHANT_LOG_FAILURE',
}

export enum GET_TRANSACTION_FEE_LOG {
  REQUEST = 'GET_TRANSACTION_FEE_LOG_REQUEST',
  SUCCESS = 'GET_TRANSACTION_FEE_LOG_SUCESSS',
  FAILURE = 'GET_TRANSACTION_FEE_LOG_FAILURE',
}

export enum UPDATE_CONTRACT_MERCHANT {
  REQUEST = 'UPDATE_CONTRACT_MERCHANT_REQUEST',
  SUCCESS = 'UPDATE_CONTRACT_MERCHANT_SUCESSS',
  FAILURE = 'UPDATE_CONTRACT_MERCHANT_FAILURE',
}

export enum RESEND_MAIL_APPROVAL {
  REQUEST = 'RESEND_MAIL_APPROVAL_REQUEST',
  SUCCESS = 'RESEND_MAIL_APPROVAL_SUCESSS',
  FAILURE = 'RESEND_MAIL_APPROVAL_FAILURE',
}

export enum CREATE_MANUAL_CROSSCHECK_MERCHANT {
  REQUEST = 'CREATE_MANUAL_CROSSCHECK_MERCHANT_REQUEST',
  SUCCESS = 'CREATE_MANUAL_CROSSCHECK_MERCHANT_SUCESSS',
  FAILURE = 'CREATE_MANUAL_CROSSCHECK_MERCHANT_FAILURE',
}

export enum DISABLE_MAIL_SETTLEMENT_MERCHANT {
  REQUEST = 'DISABLE_MAIL_SETTLEMENT_MERCHANT_REQUEST',
  SUCCESS = 'DISABLE_MAIL_SETTLEMENT_MERCHANT_SUCESSS',
  FAILURE = 'DISABLE_MAIL_SETTLEMENT_MERCHANT_FAILURE',
}

export enum REQUEST_UPDATE_ACTIVE_MERCHANT {
  REQUEST = 'REQUEST_UPDATE_ACTIVE_MERCHANT_REQUEST',
  SUCCESS = 'REQUEST_UPDATE_ACTIVE_MERCHANT_SUCESSS',
  FAILURE = 'REQUEST_UPDATE_ACTIVE_MERCHANT_FAILURE',
}

export enum SEARCH_EXPERTISE_MERCHANT {
  REQUEST = 'SEARCH_EXPERTISE_MERCHANT_REQUEST',
  SUCCESS = 'SEARCH_EXPERTISE_MERCHANT_SUCCESS',
  FAILURE = 'SEARCH_EXPERTISE_MERCHANT_FAILURE',
}

export enum MC_SDK_LIST {
  REQUEST = 'MC_SDK_LIST_REQUEST',
  SUCCESS = 'MC_SDK_LIST_SUCCESS',
  FAILURE = 'MC_SDK_LIST_FAILURE',
}
