export enum MERCHANT_EXPORT {
  REQUEST = 'MERCHANT_EXPORT_REQUEST',
  SUCCESS = 'MERCHANT_EXPORT_SUCCESS',
  FAILURE = 'MERCHANT_EXPORT_FAILURE',
  PENDING = 'MERCHANT_EXPORT_PENDING',
}

export enum MERCHANT_EXPORT_SOXKET {
  REQUEST = 'MERCHANT_EXPORT_SOXKET_REQUEST',
  SUCCESS = 'MERCHANT_EXPORT_SOXKET_SUCCESS',
  FAILURE = 'MERCHANT_EXPORT_SOXKET_FAILURE',
  PENDING = 'MERCHANT_EXPORT_SOXKET_PENDING',
}
