export enum SEARCH_MERCHANT_INFO {
  REQUEST = 'SEARCH_MERCHANT_INFO_REQUEST',
  SUCCESS = 'SEARCH_MERCHANT_INFO_SUCCESS',
  FAILURE = 'SEARCH_MERCHANT_INFO_FAILURE',
}

export enum SEARCH_MERCHANT_INFO_LIST {
  REQUEST = 'SEARCH_MERCHANT_INFO_LIST_REQUEST',
  SUCCESS = 'SEARCH_MERCHANT_INFO_LIST_SUCCESS',
  FAILURE = 'SEARCH_MERCHANT_INFO_LIST_FAILURE',
}


export enum UPDATE_MERCHANT_INFO {
  REQUEST = 'UPDATE_MERCHANT_INFO_REQUEST',
  SUCCESS = 'UPDATE_MERCHANT_INFO_SUCCESS',
  FAILURE = 'UPDATE_MERCHANT_INFO_FAILURE',
}

export enum GET_MERCHANT_LINKED_BANKS {
  REQUEST = 'GET_MERCHANT_LINKED_BANKS_REQUEST',
  SUCCESS = 'GET_MERCHANT_LINKED_BANKS_SUCCESS',
  FAILURE = 'GET_MERCHANT_LINKED_BANKS_FAILURE',
}

export enum GET_MERCHANT_TRANSACTION_HISTORY {
  REQUEST = 'GET_MERCHANT_WALLET_HISTORY_REQUEST',
  SUCCESS = 'GET_MERCHANT_WALLET_HISTORY_SUCCESS',
  FAILURE = 'GET_MERCHANT_WALLET_HISTORY_FAILURE',
}

export enum GET_MERCHANT_TRANSACTION_REPORT {
  REQUEST = "GET_MERCHANT_TRANSACTION_REPORT_REQUEST",
  SUCCESS = "GET_MERCHANT_TRANSACTION_REPORT_SUCCESS",
  FAILURE = "GET_MERCHANT_TRANSACTION_REPORT_FAILURE",
}

export enum GET_MERCHANT_SESSIONS {
  REQUEST = 'GET_MERCHANT_SESSIONS_REQUEST',
  SUCCESS = 'GET_MERCHANT_SESSIONS_SUCCESS',
  FAILURE = 'GET_MERCHANT_SESSIONS_FAILURE',
}

export enum GET_MERCHANT_CHANGE_HISTORY {
  REQUEST = 'GET_MERCHANT_CHANGE_HISTORY_REQUEST',
  SUCCESS = 'GET_MERCHANT_CHANGE_HISTORY_SUCCESS',
  FAILURE = 'GET_MERCHANT_CHANGE_HISTORY_FAILURE',
}

export enum UPDATE_CONFIG_ACCOUNT {
  REQUEST = 'UPDATE_CONFIG_ACCOUNT_REQUEST',
  SUCCESS = 'UPDATE_CONFIG_ACCOUNT_SUCCESS',
  FAILURE = 'UPDATE_CONFIG_ACCOUNT_FAILURE',
}

export enum RESET_MERCHANT_PASSWORD {
  REQUEST = 'ESET_MERCHANT_PASSWORD_REQUEST',
  SUCCESS = 'ESET_MERCHANT_PASSWORD_SUCCESS',
  FAILURE = 'ESET_MERCHANT_PASSWORD_FAILURE',
}

export enum REQUEST_CANCEL_MERCHANT_WALLET {
  REQUEST = 'REQUEST_CANCEL_MERCHANT_WALLET_REQUEST',
  SUCCESS = 'REQUEST_CANCEL_MERCHANT_WALLET_SUCCESS',
  FAILURE = 'REQUEST_CANCEL_MERCHANT_WALLET_FAILURE',
}

export enum UNLOCK_MERCHANT_KYC {
  REQUEST = 'UNLOCK_MERCHANT_KYC_REQUEST',
  SUCCESS = 'UNLOCK_MERCHANT_KYC_SUCCESS',
  FAILURE = 'UNLOCK_MERCHANT_KYC_FAILURE',
}

export enum UPDATE_ACCOUNT_INFO_EWALLET {
  REQUEST = 'UPDATE_ACCOUNT_INFO_EWALLET_REQUEST',
  SUCCESS = 'UPDATE_ACCOUNT_INFO_EWALLET_SUCCESS',
  FAILURE = 'UPDATE_ACCOUNT_INFO_EWALLET_FAILURE',
}

export enum RESET_SEARCH_MERCHANT {
  REQUEST = 'RESET_SEARCH_MERCHANT_REQUEST',
  SUCCESS = 'RESET_SEARCH_MERCHANT_SUCCESS',
  FAILURE = 'RESET_SEARCH_MERCHANT_FAILURE',
}
