export enum REQUEST_MESSAGE {
  REQUEST = 'REQUEST_MESSAGE_REQUEST',
  SUCCESS = 'REQUEST_MESSAGE_SUCCESS',
  FAILURE = 'REQUEST_MESSAGE_FAILURE',
}

export enum REQUEST_CHANGED_MESSAGE {
  REQUEST = 'REQUEST_CHANGED_MESSAGE_REQUEST',
  SUCCESS = 'REQUEST_CHANGED_MESSAGE_SUCCESS',
  FAILURE = 'REQUEST_CHANGED_MESSAGE_FAILURE',
}

export enum REQUEST_SEND_MAIL {
  REQUEST = 'REQUEST_SEND_MAIL_REQUEST',
  SUCCESS = 'REQUEST_SEND_MAIL_SUCCESS',
  FAILURE = 'REQUEST_SEND_MAIL_FAILURE',
}

export enum SEND_TEST_MAIL {
  REQUEST = 'SEND_TEST_MAIL_REQUEST',
  SUCCESS = 'SEND_TEST_MAIL_SUCCESS',
  FAILURE = 'SEND_TEST_MAIL_FAILURE',
}
