export enum GET_HISTORY {
  REQUEST = "GET_HISTORY_REQUEST",
  SUCCESS = "GET_HISTORY_SUCCESS",
  FAILURE = "GET_HISTORY_FAILURE",
}

export enum SEND_SMS {
  REQUEST = "SEND_SMS_REQUEST",
  SUCCESS = "SEND_SMS_SUCCESS",
  FAILURE = "SEND_SMS_FAILURE",
}