
export enum GET_OVERVIEW_REPORT_WALLET {
  REQUEST = 'GET_OVERVIEW_REPORT_WALLET_REQUEST',
  SUCCESS = 'GET_OVERVIEW_REPORT_WALLET_SUCCESS',
  FAILURE = 'GET_OVERVIEW_REPORT_WALLET_FAILURE',
}

export enum GET_TOTAL_USER {
  REQUEST = 'GET_TOTAL_USER_REQUEST',
  SUCCESS = 'GET_TOTAL_USER_SUCCESS',
  FAILURE = 'GET_TOTAL_USER_FAILURE',
}

export enum REPORT_EWALLET_DAILY {
  REQUEST = 'REPORT_EWALLET_DAILY_REQUEST',
  SUCCESS = 'REPORT_EWALLET_DAILY_SUCCESS',
  FAILURE = 'REPORT_EWALLET_DAILY_FAILURE',
}

export enum ACCOUNT_STATMENT_SECURE_WALLET {
  REQUEST = 'ACCOUNT_STATMENT_SECURE_WALLET_REQUEST',
  SUCCESS = 'ACCOUNT_STATMENT_SECURE_WALLET_SUCCESS',
  FAILURE = 'ACCOUNT_STATMENT_SECURE_WALLET_FAILURE',
}