
export enum GET_LIST_POBO {
    REQUEST = 'GET_LIST_POBO_REQUEST',
    SUCCESS = 'GET_LIST_POBO_SUCCESS',
    FAILURE = 'GET_LIST_POBO_FAILURE',
}

export enum CHANGE_POBO {
    REQUEST = 'CHANGE_POBO_REQUEST',
    SUCCESS = 'CHANGE_POBO_SUCCESS',
    FAILURE = 'CHANGE_POBO_FAILURE',
}

export enum EXPORT_POBO_ORDER {
    REQUEST = "EXPORT_POBO_ORDER_REQUEST",
    SUCCESS = "EXPORT_POBO_ORDER_SUCCESS",
    FAILURE = "EXPORT_POBO_ORDER_FAILURE",
    PENDING = 'EXPORT_POBO_ORDER_PENDING'
}

export enum EXPORT_WITH_DRAW {
    REQUEST = "EXPORT_WITH_DRAW_REQUEST",
    SUCCESS = "EXPORT_WITH_DRAW_SUCCESS",
    FAILURE = "EXPORT_WITH_DRAW_FAILURE",
    PENDING = 'EXPORT_WITH_DRAW_PENDING'
}