export enum GET_LIST_PROCESSING_FLOW {
  REQUEST = "GET_LIST_PROCESSING_FLOW_REQUEST",
  SUCCESS = "GET_LIST_PROCESSING_FLOW_SUCCESS",
  FAILURE = "GET_LIST_PROCESSING_FLOW_FAILURE",
}

export enum CREATE_PROCESSING_FLOW {
  REQUEST = "CREATE_PROCESSING_FLOW_REQUEST",
  SUCCESS = "CREATE_PROCESSING_FLOW_SUCCESS",
  FAILURE = "CREATE_PROCESSING_FLOW_FAILURE",
}

export enum UPDATE_PROCESSING_FLOW {
  REQUEST = "UPDATE_PROCESSING_FLOW_REQUEST",
  SUCCESS = "UPDATE_PROCESSING_FLOW_SUCCESS",
  FAILURE = "UPDATE_PROCESSING_FLOW_FAILURE",
}

export enum GET_PENDING_LIST_MERCHANT {
  REQUEST = "GET_PENDING_LIST_MERCHANT_REQUEST",
  SUCCESS = "GET_PENDING_LIST_MERCHANT_SUCCESS",
  FAILURE = "GET_PENDING_LIST_MERCHANT_FAILURE",
}

export enum GET_TOTAL_PENDING_MERCHANT {
  REQUEST = "GET_TOTAL_PENDING_MERCHANT_REQUEST",
  SUCCESS = "GET_TOTAL_PENDING_MERCHANT_SUCCESS",
  FAILURE = "GET_TOTAL_PENDING_MERCHANT_FAILURE",
}