export enum GET_TOP_MERCHANT_CATEGORY {
    REQUEST = 'GET_TOP_MERCHANT_CATEGORY_REQUEST',
    SUCCESS = 'GET_TOP_MERCHANT_CATEGORY_SUCCESS',
    FAILURE = 'GET_TOP_MERCHANT_CATEGORY_FAILURE',
  }
  
  export enum GET_DATA_REPORT_MC_AMOUNT {
    REQUEST = 'GET_DATA_REPORT_MC_AMOUNT_REQUEST',
    SUCCESS = 'GET_DATA_REPORT_MC_AMOUNT_SUCCESS',
    FAILURE = 'GET_DATA_REPORT_MC_AMOUNT_FAILURE',
  }
   
  export enum GET_DATA_QUANTITY_MERCHANT {
    REQUEST = 'GET_DATA_QUANTITY_MERCHANT_REQUEST',
    SUCCESS = 'GET_DATA_QUANTITY_MERCHANT_SUCCESS',
    FAILURE = 'GET_DATA_QUANTITY_MERCHANT_FAILURE',
  }