export enum GET_DATA_REPORT_TRANSACTION_SUPPLIER {
    REQUEST = "GET_DATA_REPORT_TRANSACTION_SUPPLIER_REQUEST",
    SUCCESS = "GET_DATA_REPORT_TRANSACTION_SUPPLIER_SUCCESS",
    FAILURE = "GET_DATA_REPORT_TRANSACTION_SUPPLIER_FAILURE",
  }