export enum GET_LIST_REPORT_BILL {
    REQUEST = "GET_LIST_REPORT_BILL_REQUEST",
    SUCCESS = "GET_LIST_REPORT_BILL_SUCCESS",
  FAILURE = "GET_LIST_REPORT_BILL_FAILURE",
  DELETE = "GET_LIST_REPORT_BILL_DELETE",
}
  
export enum GET_LIST_REPORT_TOP {
  REQUEST = "GET_LIST_REPORT_TOP_REQUEST",
  SUCCESS = "GET_LIST_REPORT_TOP_SUCCESS",
FAILURE = "GET_LIST_REPORT_TOP_FAILURE",
DELETE = "GET_LIST_REPORT_TOP_DELETE",
}