export enum GET_REVENUE_STATISTICS {
  REQUEST = 'GET_REVENUE_STATISTICS_REQUEST',
  SUCCESS = 'GET_REVENUE_STATISTICS_SUCCESS',
  FAILURE = 'GET_REVENUE_STATISTICS_FAILURE',
}

export enum GET_SUM_REVENUE_STATISTICS {
  REQUEST = 'GET_SUM_REVENUE_STATISTICS_REQUEST',
  SUCCESS = 'GET_SUM_REVENUE_STATISTICS_SUCCESS',
  FAILURE = 'GET_SUM_REVENUE_STATISTICS_FAILURE',
}

export enum GET_DETAIL_REVENUE_STATISTICS {
  REQUEST = 'GET_DETAIL_REVENUE_STATISTICS_REQUEST',
  SUCCESS = 'GET_DETAIL_REVENUE_STATISTICS_SUCCESS',
  FAILURE = 'GET_DETAIL_REVENUE_STATISTICS_FAILURE',
}

export enum SEND_MAIL_MERCHANT_REPORT_CROSS_CHECK {
  REQUEST = 'SEND_MAIL_MERCHANT_REPORT_CROSS_CHECK_REQUEST',
  SUCCESS = 'SEND_MAIL_MERCHANT_REPORT_CROSS_CHECK_SUCCESS',
  FAILURE = 'SEND_MAIL_MERCHANT_REPORT_CROSS_CHECK_FAILURE',
}
