export enum GET_REPORT_WALLET {
  REQUEST = 'GET_REPORT_WALLET_REQUEST',
  SUCCESS = 'GET_REPORT_WALLET_SUCCESS',
  FAILURE = 'GET_REPORT_WALLET_FAILURE',
}

export enum GET_BALANCE_REPORT_WALLET {
  REQUEST = 'GET_BALANCE_REPORT_WALLET_REQUEST',
  SUCCESS = 'GET_BALANCE_REPORT_WALLET_SUCCESS',
  FAILURE = 'GET_BALANCE_REPORT_WALLET_FAILURE',
}

export enum GET_INFO_KYC_REPORT_WALLET {
  REQUEST = 'GET_INFO_KYC_REPORT_WALLET_REQUEST',
  SUCCESS = 'GET_INFO_KYC_REPORT_WALLET_SUCCESS',
  FAILURE = 'GET_INFO_KYC_REPORT_WALLET_FAILURE',
}
