export enum GET_LIST_REPORT_AGENT {
  REQUEST = "GET_LIST_REPORT_AGENT_REQUEST",
  SUCCESS = "GET_LIST_REPORT_AGENT_SUCCESS",
  FAILURE = "GET_LIST_REPORT_AGENT_FAILURE",
  DELETE = "GET_LIST_REPORT_AGENT_DELETE",
}
  
export enum GET_LIST_REPORT_SYSTEM_TRANSACTION {
  REQUEST = "GET_LIST_REPORT_SYSTEM_TRANSACTION_REQUEST",
  SUCCESS = "GET_LIST_REPORT_SYSTEM_TRANSACTION_SUCCESS",
  FAILURE = "GET_LIST_REPORT_SYSTEM_TRANSACTION_FAILURE",
  DELETE = "GET_LIST_REPORT_SYSTEM_TRANSACTION_DELETE",
  }