export enum GET_REPORT_EWALLET_MC {
  REQUEST = "GET_REPORT_EWALLET_MC_REQUEST",
  SUCCESS = "GET_REPORT_EWALLET_MC_SUCCESS",
  FAILURE = "GET_REPORT_EWALLET_MC_FAILURE",
}

export enum EXPORT_REPORT_EWALLET_MC {
  REQUEST = "EXPORT_REPORT_EWALLET_MC_REQUEST",
  SUCCESS = "EXPORT_REPORT_EWALLET_MC_SUCCESS",
  FAILURE = "EXPORT_REPORT_EWALLET_MC_FAILURE",
  PENDING = 'EXPORT_REPORT_EWALLET_MC_PENDING'
}