export enum GET_REPORT_AGENT {
  REQUEST = 'GET_REPORT_AGENT_REQUEST',
  SUCCESS = 'GET_REPORT_AGENT_SUCCESS',
  FAILURE = 'GET_REPORT_AGENT_FAILURE',
  DELETE = 'GET_REPORT_AGENT_DELETE',
}

export enum REPORT_SYSTEM_TRANSACTION {
  REQUEST = 'REPORT_SYSTEM_TRANSACTION_REQUEST',
  SUCCESS = 'REPORT_SYSTEM_TRANSACTION_SUCCESS',
  FAILURE = 'REPORT_SYSTEM_TRANSACTION_FAILURE',
  DELETE = 'REPORT_SYSTEM_TRANSACTION_DELETE',
}
