export enum REPORT_EWALLET_SERVICE {
  REQUEST = 'REPORT_EWALLET_SERVICE_REQUEST',
  SUCCESS = 'REPORT_EWALLET_SERVICE_SUCCESS',
  FAILURE = 'REPORT_EWALLET_SERVICE_FAILURE',
}
export enum APP_SERVICE_ITEM {
  REQUEST = 'APP_SERVICE_ITEM_REQUEST',
  SUCCESS = 'APP_SERVICE_ITEM_SUCCESS',
  FAILURE = 'APP_SERVICE_ITEM_FAILURE',
}
export enum GET_EWALLET_ENUM_SERVICE {
  REQUEST = 'GET_EWALLET_ENUM_SERVICE_REQUEST',
  SUCCESS = 'GET_EWALLET_ENUM_SERVICE_SUCCESS',
  FAILURE = 'GET_EWALLET_ENUM_SERVICE_FAILURE',
}
