export enum GET_LIST_SCOPE {
  REQUEST = 'LIST_SCOPE_REQUEST',
  SUCCESS = 'LIST_SCOPE_SUCCESS',
  FAILURE = 'LIST_SCOPE_FAILURE',
}

export enum GET_LIST_ROLE {
  REQUEST = 'LIST_ROLE_REQUEST',
  SUCCESS = 'LIST_ROLE_SUCCESS',
  FAILURE = 'LIST_ROLE_FAILURE',
}

export enum UPDATE_SCOPE_ROLE {
  REQUEST = 'UPDATE_SCOPE_ROLE_REQUEST',
  SUCCESS = 'UPDATE_SCOPE_ROLE_SUCCESS',
  FAILURE = 'UPDATE_SCOPE_ROLE_FAILURE',
}
