export enum GET_REPORT_SALARY_ADVANCE {
  REQUEST = 'GET_REPORT_SALARY_ADVANCE_REQUEST',
  SUCCESS = 'GET_REPORT_SALARY_ADVANCE_SUCCESS',
  FAILURE = 'GET_REPORT_SALARY_ADVANCE_FAILURE',
}

export enum GET_SALARY_ADVANCE {
  REQUEST = 'GET_SALARY_ADVANCE_REQUEST',
  SUCCESS = 'GET_SALARY_ADVANCE_SUCCESS',
  FAILURE = 'GET_SALARY_ADVANCE_FAILURE',
}
