export enum GET_SCOPE {
  REQUEST = 'GET_SCOPE_REQUEST',
  SUCCESS = 'GET_SCOPE_SUCCESS',
  FAIL = 'GET_SCOPE_FAIL',
}

export enum CREATE_SCOPE {
  REQUEST = 'CREATE_SCOPE_REQUEST',
  SUCCESS = 'CREATE_SCOPE_SUCCESS',
  FAIL = 'CREATE_SCOPE_FAIL',
}

export enum UPDATE_SCOPE {
  REQUEST = 'UPDATE_SCOPE_REQUEST',
  SUCCESS = 'UPDATE_SCOPE_SUCCESS',
  FAIL = 'UPDATE_SCOPE_FAIL',
}

export enum DELETE_SCOPE {
  REQUEST = 'DELETE_SCOPE_REQUEST',
  SUCCESS = 'DELETE_SCOPE_SUCCESS',
  FAIL = 'DELETE_SCOPE_FAIL',
}

export enum GET_LIST_MC_SCOPE {
  REQUEST = 'GET_LIST_MC_SCOPE_REQUEST',
  SUCCESS = 'GET_LIST_MC_SCOPE_SUCCESS',
  FAIL = 'GET_LIST_MC_SCOPE_FAIL',
}

export enum DELETE_MC_SCOPE {
  REQUEST = 'DELETE_MC_SCOPE_REQUEST',
  SUCCESS = 'DELETE_MC_SCOPE_SUCCESS',
  FAIL = 'DELETE_MC_SCOPE_FAIL',
}

export enum UPDATE_MC_SCOPE {
  REQUEST = 'UPDATE_MC_SCOPE_REQUEST',
  SUCCESS = 'UPDATE_MC_SCOPE_SUCCESS',
  FAIL = 'UPDATE_MC_SCOPE_FAIL',
}

export enum CREATE_MC_SCOPE {
  REQUEST = 'CREATE_MC_SCOPE_REQUEST',
  SUCCESS = 'CREATE_MC_SCOPE_SUCCESS',
  FAIL = 'CREATE_MC_SCOPE_FAIL',
}
