export enum GET_SETTING_DEPOSIT {
  REQUEST = 'GET_SETTING_DEPOSIT_REQUEST',
  SUCCESS = 'GET_SETTING_DEPOSIT_SUCCESS',
  FAILURE = 'GET_SETTING_DEPOSIT_FAILURE',
}

export enum UPDATE_SETTING_DEPOSIT {
  REQUEST = 'UPDATE_SETTING_DEPOSIT_REQUEST',
  SUCCESS = 'UPDATE_SETTING_DEPOSIT_SUCCESS',
  FAILURE = 'UPDATE_SETTING_DEPOSIT_FAILURE',
}

export enum CREATE_SETTING_DEPOSIT {
  REQUEST = 'CREATE_SETTING_DEPOSIT_REQUEST',
  SUCCESS = 'CREATE_SETTING_DEPOSIT_SUCCESS',
  FAILURE = 'CREATE_SETTING_DEPOSIT_FAILURE',
}
