export enum GET_SETTING_SYSTEM {
  REQUEST = 'GET_SETTING_SYSTEM_REQUEST',
  SUCCESS = 'GET_SETTING_SYSTEM_SUCCESS',
  FAILURE = 'GET_SETTING_SYSTEM_FAILURE',
}

export enum UPDATE_SETTING_SYSTEM {
  REQUEST = 'UPDATE_SETTING_SYSTEM_REQUEST',
  SUCCESS = 'UPDATE_SETTING_SYSTEM_SUCCESS',
  FAILURE = 'UPDATE_SETTING_SYSTEM_FAILURE',
}
