export enum GET_REVENUE_STATISTICS_SDK {
  REQUEST = 'GET_REVENUE_STATISTICS_SDK_REQUEST',
  SUCCESS = 'GET_REVENUE_STATISTICS_SDK_SUCCESS',
  FAILURE = 'GET_REVENUE_STATISTICS_SDK_FAILURE',
}
export enum GET_SUM_REVENUE_STATISTICS_SDK {
  REQUEST = 'GET_SUM_REVENUE_STATISTICS_SDK_REQUEST',
  SUCCESS = 'GET_SUM_REVENUE_STATISTICS_SDK_SUCCESS',
  FAILURE = 'GET_SUM_REVENUE_STATISTICS_SDK_FAILURE',
}
