export enum GET_LIST_STORE {
  REQUEST = 'GET_LIST_STORE_REQUEST',
  SUCCESS = 'GET_LIST_STORE_SUCCESS',
  FAILURE = 'GET_LIST_STORE_FAILURE',
}

export enum UPDATE_STORE {
  REQUEST = 'UPDATE_STORE_REQUEST',
  SUCCESS = 'UPDATE_STORE_SUCCESS',
  FAILURE = 'UPDATE_STORE_FAILURE',
}

export enum GET_LOG_STORE {
  REQUEST = 'GET_LOG_STORE_REQUEST',
  SUCCESS = 'GET_LOG_STORE_SUCCESS',
  FAILURE = 'GET_LOG_STORE_FAILURE',
}

export enum APPROVAL_ALIPAY_TYPES {
  REQUEST = 'APPROVAL_ALIPAY_STORE_REQUEST',
  SUCCESS = 'APPROVAL_ALIPAY_STORE_SUCCESS',
  FAILURE = 'APPROVAL_ALIPAY_STORE_FAILURE',
}

export enum CHECK_STATUS_ALIPAY {
  REQUEST = 'CHECK_ALIPAY_STORE_REQUEST',
  SUCCESS = 'CHECK_ALIPAY_STORE_SUCCESS',
  FAILURE = 'CHECK_ALIPAY_STORE_FAILURE',
}

export enum GET_DELEGATE_STORE {
  REQUEST = 'GET_DELEGATE_STORE_REQUEST',
  SUCCESS = 'GET_DELEGATE_STORE_SUCCESS',
  FAILURE = 'GET_DELEGATE_STORE_FAILURE',
}

export enum GET_MERCHANT_STORE {
  REQUEST = 'GET_MERCHANT_STORE_REQUEST',
  SUCCESS = 'GET_MERCHANT_STORE_SUCCESS',
  FAILURE = 'GET_MERCHANT_STORE_FAILURE',
}
