export enum GET_LIST_SUPPLIER_MANAGE {
  REQUEST = 'GET_LIST_SUPPLIER_MANAGE_REQUEST',
  SUCCESS = 'GET_LIST_SUPPLIER_MANAGE_SUCCESS',
  FAILURE = 'GET_LIST_SUPPLIER_MANAGE_FAILURE',
}

export enum GET_DETAIL_SUPPLIER {
  REQUEST = 'GET_DETAIL_SUPPLIER_REQUEST',
  SUCCESS = 'GET_DETAIL_SUPPLIER_SUCCESS',
  FAILURE = 'GET_DETAIL_SUPPLIER_FAILURE',
  CLEAR = 'GET_DETAIL_SUPPLIER_CLEAR',
}

export enum EXPORT_SUPPLIER_MANAGE {
  REQUEST = 'EXPORT_SUPPLIER_MANAGE_REQUEST',
  SUCCESS = 'EXPORT_SUPPLIER_MANAGE_SUCCESS',
  FAILURE = 'EXPORT_SUPPLIER_MANAGE_FAILURE',
}
export enum GET_DETAIL_ID_SUPPLIER {
  REQUEST = 'GET_DETAIL_ID_SUPPLIER_REQUEST',
  SUCCESS = 'GET_DETAIL_ID_SUPPLIER_SUCCESS',
  FAILURE = 'GET_DETAIL_ID_SUPPLIER_FAILURE',
  CLEAR = 'GET_DETAIL_ID_SUPPLIER_CLEAR',
}

export enum GET_TRANSACTION_BANK_STATE {
  REQUEST = 'GET_TRANSACTION_BANK_STATE_REQUEST',
  SUCCESS = 'GET_TRANSACTION_BANK_STATE_SUCCESS',
  FAILURE = 'GET_TRANSACTION_BANK_STATE_FAILURE',
}

//ngân hàng hợp tác công thanh toán
export enum GET_CTT_COOPBANK_LIST {
  REQUEST = 'GET_CTT_COOPBANK_LIST_REQUEST',
  SUCCESS = 'GET_CTT_COOPBANK_LIST_SUCCESS',
  FAILURE = 'GET_CTT_COOPBANK_LIST_FAILURE',
  REFRESH = 'GET_CTT_COOPBANK_LIST_REFRESH',
}
export enum ADD_CTT_COOPBANK {
  REQUEST = 'ADD_CTT_COOPBANK_REQUEST',
  SUCCESS = 'ADD_CTT_COOPBANK_SUCCESS',
  FAILURE = 'ADD_CTT_COOPBANK_FAILURE',
  REFRESH = 'ADD_CTT_COOPBANK_REFRESH',
}
export enum UPDATE_CTT_COOPBANK {
  REQUEST = 'UPDATE_CTT_COOPBANK_REQUEST',
  SUCCESS = 'UPDATE_CTT_COOPBANK_SUCCESS',
  FAILURE = 'UPDATE_CTT_COOPBANK_FAILURE',
  REFRESH = 'UPDATE_CTT_COOPBANK_REFRESH',
}

