export enum GET_TELCO_PRICE {
  REQUEST = 'GET_TELCO_PRICE_REQUEST',
  SUCCESS = 'GET_TELCO_PRICE_SUCCESS',
  FAILURE = 'GET_TELCO_PRICE_FAILURE',
}

export enum GET_TELCO_DATE {
  REQUEST = 'GET_TELCO_DATE_REQUEST',
  SUCCESS = 'GET_TELCO_DATE_SUCCESS',
  FAILURE = 'GET_TELCO_DATE_FAILURE',
}
