export enum GET_LIST_TEMPLATE {
  REQUEST = 'GET_LIST_TEMPLATE_REQUEST',
  SUCCESS = 'GET_LIST_TEMPLATE_SUCCESS',
  FAILURE = 'GET_LIST_TEMPLATE_FAILURE',
}

export enum CREATE_TEMPLATE {
  REQUEST = 'CREATE_TEMPLATE_REQUEST',
  SUCCESS = 'CREATE_TEMPLATE_SUCCESS',
  FAILURE = 'CREATE_TEMPLATE_FAILURE',
}

export enum UPDATE_TEMPLATE {
  REQUEST = 'UPDATE_TEMPLATE_REQUEST',
  SUCCESS = 'UPDATE_TEMPLATE_SUCCESS',
  FAILURE = 'UPDATE_TEMPLATE_FAILURE',
}

export enum GET_LIST_TEMPLATE_WALLET {
  REQUEST = 'GET_LIST_TEMPLATE_WALLET_REQUEST',
  SUCCESS = 'GET_LIST_TEMPLATE_WALLET_SUCCESS',
  FAILURE = 'GET_LIST_TEMPLATE_WALLET_FAILURE',
}

export enum CREATE_TEMPLATE_WALLET {
  REQUEST = 'CREATE_TEMPLATE_WALLET_REQUEST',
  SUCCESS = 'CREATE_TEMPLATE_WALLET_SUCCESS',
  FAILURE = 'CREATE_TEMPLATE_WALLET_FAILURE',
}

export enum UPDATE_TEMPLATE_WALLET {
  REQUEST = 'UPDATE_TEMPLATE_WALLET_REQUEST',
  SUCCESS = 'UPDATE_TEMPLATE_WALLET_SUCCESS',
  FAILURE = 'UPDATE_TEMPLATE_WALLET_FAILURE',
}