export enum GET_TOP_TRANSFER {
  REQUEST = 'GET_TOP_TRANSFER_REQUEST',
  SUCCESS = 'GET_TOP_TRANSFER_SUCCESS',
  FAILURE = 'GET_TOP_TRANSFER_FAILURE',
}

export enum GET_DATA_TOP_10_WALLET {
  REQUEST = 'GET_DATA_TOP_10_WALLET_REQUEST',
  SUCCESS = 'GET_DATA_TOP_10_WALLET_SUCCESS',
  FAILURE = 'GET_DATA_TOP_10_WALLET_FAILURE',
}

export enum GET_DATA_TOP_10_WALLET_AMOUNT {
  REQUEST = 'GET_DATA_TOP_10_WALLET_AMOUNT_REQUEST',
  SUCCESS = 'GET_DATA_TOP_10_WALLET_AMOUNT_SUCCESS',
  FAILURE = 'GET_DATA_TOP_10_WALLET_AMOUNT_FAILURE',
}