export enum GET_TOP_UP_PHONE {
    REQUEST = 'GET_TOP_UP_PHONE_REQUEST',
    SUCCESS = 'GET_TOP_UP_PHONE_SUCCESS',
  FAILURE = 'GET_TOP_UP_PHONE_FAILURE',
  DELETE = 'GET_TOP_UP_PHONE_DELETE',
  }
  
 