export enum GET_MISMATCH_TRANSACTIONS {
  REQUEST = "GET_MISMATCH_TRANSACTIONS_REQUEST",
  SUCCESS = "GET_MISMATCH_TRANSACTIONS_SUCCESS",
  FAILURE = "GET_MISMATCH_TRANSACTIONS_FAILURE",
}

export enum UPDATE_MISMATCH_TRANSACTIONS {
  REQUEST = "UPDATE_MISMATCH_TRANSACTIONS_REQUEST",
  SUCCESS = "UPDATE_MISMATCH_TRANSACTIONS_SUCCESS",
  FAILURE = "UPDATE_MISMATCH_TRANSACTIONS_FAILURE",
}

export enum EXPORT_MISMATCH_TRANSACTIONS {
  REQUEST = "EXPORT_MISMATCH_TRANSACTIONS_REQUEST",
  PENDING = "EXPORT_MISMATCH_TRANSACTIONS_PENDING",
  SUCCESS = "EXPORT_MISMATCH_TRANSACTIONS_SUCCESS",
  FAILURE = "EXPORT_MISMATCH_TRANSACTIONS_FAILURE",
}