export enum GET_LIST_TRANSACTION {
  REQUEST = 'GET_LIST_TRANSACTION_REQUEST',
  SUCCESS = 'GET_LIST_TRANSACTION_SUCCESS',
  FAILURE = 'GET_LIST_TRANSACTION_FAILURE',
}

export enum GET_DETAIL_TRANSACTION {
  REQUEST = 'GET_DETAIL_TRANSACTION_REQUEST',
  SUCCESS = 'GET_DETAIL_TRANSACTION_SUCCESS',
  FAILURE = 'GET_DETAIL_TRANSACTION_FAILURE',
}

export enum LOADING_DRAWER {
  SHOW = 'LOADING_DRAWER_SHOW',
  HIDE = 'LOADING_DRAWER_HIDE',
}

export enum LOADING_MODAL {
  SHOW = 'LOADING_MODAL_SHOW',
  HIDE = 'LOADING_MODAL_HIDE',
}

export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export enum REFUND_TRANSACTION {
  REQUEST = 'REFUND_TRANSACTION_REQUEST',
  SUCCESS = 'REFUND_TRANSACTION_SUCCESS',
  FAILURE = 'REFUND_TRANSACTION_FAILURE',
}

export enum GET_REFUND_AMOUNT_TRANSACTION {
  REQUEST = "GET_REFUND_AMOUNT_TRANSACTION_REQUEST",
  SUCCESS = "GET_REFUND_AMOUNT_TRANSACTION_SUCCESS",
  FAILURE = "GET_REFUND_AMOUNT_TRANSACTION_FAILURE",
}

export enum CANCEL_TRANSACTION {
  REQUEST = 'CANCEL_TRANSACTION_REQUEST',
  SUCCESS = 'CANCEL_TRANSACTION_SUCCESS',
  FAILURE = 'CANCEL_TRANSACTION_FAILURE',
}

export enum ADD_PAYINT{
  REQUEST = 'ADD_PAYINT_REQUEST',
  SUCCESS = 'ADD_PAYINT_SUCCESS',
  FAILURE = 'ADD_PAYINT_FAIL',
}

export enum REVIEW_PAYINT {
  REQUEST = 'REVIEW_PAYINT_REQUEST',
  SUCCESS = 'REVIEW_PAYINT_SUCCESS',
  FAILURE = 'REVIEW_PAYINT_FAIL',
}

export enum APPROVE_PAYINT{
  REQUEST = 'APPROVE_PAYINT_REQUEST',
  SUCCESS = 'APPROVE_PAYINT_SUCCESS',
  FAILURE = 'APPROVE_PAYINT_FAIL',
}