export enum TRANSACTION_MANAGE_EXPORT {
  REQUEST = 'TRANSACTION_MANAGE_EXPORT_REQUEST',
  SUCCESS = 'TRANSACTION_MANAGE_EXPORT_SUCCESS',
  FAILURE = 'TRANSACTION_MANAGE_EXPORT_FAILURE',
  PENDING = 'TRANSACTION_MANAGE_EXPORT_PENDING',
}
