export enum SEARCH_USER_MERCHANT {
    REQUEST = "SEARCH_USER_MERCHANT_REQUEST",
    SUCCESS = "SEARCH_USER_MERCHANT_SUCCESS",
  FAILURE = "SEARCH_USER_MERCHANT_FAILURE",
    DELETE ="SEARCH_USER_MERCHANT_DELETE",
}

export enum CREATE_USER {
  REQUEST = "CREATE_USER_REQUEST",
  SUCCESS = "CREATE_USER_SUCCESS",
  FAILURE = "CREATE_USER_FAILURE",
}

export enum GET_LIST_ROLE_USER{
  REQUEST = "GET_LIST_ROLE_USER_REQUEST",
  SUCCESS = "GET_LIST_ROLE_USER_SUCCESS",
  FAILURE ="GET_LIST_ROLE_USER_FAILURE"
}
export enum GET_DETAIL_USER{
  REQUEST = "GET_DETAIL_USER_REQUEST",
  SUCCESS = "GET_DETAIL_USER_SUCCESS",
  FAILURE = "GET_DETAIL_USER_FAILURE",
  DELETE ="GET_DETAIL_USER_DELETE"
}
export enum UPDATE_USER{
  REQUEST = "UPDATE_USER_REQUEST",
  SUCCESS = "UPDATE_USER_SUCCESS",
  FAILURE = "UPDATE_USER_FAILURE",
}

export enum CREATE_USER_SCOPE {
  REQUEST = "CREATE_USER_SCOPE_REQUEST",
  SUCCESS = "CREATE_USER_SCOPE_SUCCESS",
  FAILURE = "CREATE_USER_SCOPE_FAILURE",
}
export enum UPDATE_USER_SCOPE {
  REQUEST = "UPDATE_USER_SCOPE_REQUEST",
  SUCCESS = "UPDATE_USER_SCOPE_SUCCESS",
  FAILURE = "UPDATE_USER_SCOPE_FAILURE",
}

export enum DELETE_USER {
  REQUEST = "DELETE_USER_REQUEST",
  SUCCESS = "DELETE_USER_SUCCESS",
  FAILURE = "DELETE_USER_FAILURE",
}