export enum GET_PAYMENT_METHOD_LIST {
  REQUEST = 'GET_PAYMENT_METHOD_LIST_REQUEST',
  SUCCESS = 'GET_PAYMENT_METHOD_LIST_SUCCESS',
  FAILURE = 'GET_PAYMENT_METHOD_LIST_FAILURE',
}

export enum GET_LOCATION_CITY_LIST {
  REQUEST = 'GET_LOCATION_CITY_LIST_REQUEST',
  SUCCESS = 'GET_LOCATION_CITY_LIST_SUCCESS',
  FAILURE = 'GET_LOCATION_CITY_LIST_FAILURE',
}



export enum GET_SUB_LOCATION_LIST {
  REQUEST = 'GET_SUB_LOCATION_LIST_REQUEST',
  SUCCESS = 'GET_SUB_LOCATION_LIST_SUCCESS',
  FAILURE = 'GET_SUB_LOCATION_LIST_FAILURE',
}

export enum GET_MCC_CODE_LIST_FULL_INFO {
  REQUEST = 'GET_MCC_CODE_LIST_FULL_INFO_REQUEST',
  SUCCESS = 'GET_MCC_CODE_LIST_FULL_INFO_SUCCESS',
  FAILURE = 'GET_MCC_CODE_LIST_FULL_INFO_FAILURE',
}

export enum GET_LOGS {
  REQUEST = 'GET_LOGS_REQUEST',
  SUCCESS = 'GET_LOGS_SUCCESS',
  FAILURE = 'GET_LOGS_FAILURE',
}

export enum GET_CHANGED_INFO_FEE {
  REQUEST = 'GET_CHANGED_INFO_FEE_REQUEST',
  SUCCESS = 'GET_CHANGED_INFO_FEE_SUCCESS',
  FAILURE = 'GET_CHANGED_INFO_FEE_FAILURE',
}

export enum GET_INFO_LIST_BANK {
  REQUEST = 'GET_INFO_LIST_BANK_REQUEST',
  SUCCESS = 'GET_INFO_LIST_BANK_SUCCESS',
  FAILURE = 'GET_INFO_LIST_BANK_FAILURE',
}

export enum UPDATE_ECOMMERCE_FEE_DEFAULT {
  REQUEST = 'UPDATE_ECOMMERCE_FEE_DEFALT_REQUEST',
  SUCCESS = 'UPDATE_ECOMMERCE_FEE_DEFALT_SUCCESS',
  FAILURE = 'UPDATE_ECOMMERCE_FEE_DEFALT_FAILURE',
}

export enum UPDATE_POBO_FEE_DEFAULT {
  REQUEST = 'UPDATE_POBO_FEE_DEFAULT_REQUEST',
  SUCCESS = 'UPDATE_POBO_FEE_DEFAULT_SUCCESS',
  FAILURE = 'UPDATE_POBO_FEE_DEFAULT_FAILURE',
}

export enum UPDATE_MCC_CODE_ITEM {
  REQUEST = 'UPDATE_MCC_CODE_ITEM_REQUEST',
  SUCCESS = 'UPDATE_MCC_CODE_ITEM_SUCCESS',
  FAILURE = 'UPDATE_MCC_CODE_ITEM_FAILURE',
}

export enum GET_APP_INFO_LIST {
  REQUEST = 'GET_APP_INFO_LIST_REQUEST',
  SUCCESS = 'GET_APP_INFO_LIST_SUCCESS',
  FAILURE = 'GET_APP_INFO_LIST_FAILURE',
}

export enum GET_MCC_CODE_LIST_PARTIAL {
  REQUEST = 'GET_MCC_CODE_LIST_PARTIAL_REQUEST',
  SUCCESS = 'GET_MCC_CODE_LIST_PARTIAL_SUCCESS',
  FAILURE = 'GET_MCC_CODE_LIST_PARTIAL_FAILURE',
}

export enum GET_PAYMENT_METHOD_FULL_TYPE {
  REQUEST = 'GET_PAYMENT_METHOD_FULL_TYPE_REQUEST',
  SUCCESS = 'GET_PAYMENT_METHOD_FULL_TYPE_SUCCESS',
  FAILURE = 'GET_PAYMENT_METHOD_FULL_TYPE_FAILURE',
}

export enum GET_CHANGE_STATE_COBO_POBO {
  REQUEST = 'GET_CHANGE_STATE_COBO_POBO_REQUEST',
  SUCCESS = 'GET_CHANGE_STATE_COBO_POBO_SUCCESS',
  FAILURE = 'GET_CHANGE_STATE_COBO_POBO_FAILURE',
}

export enum GET_DATA_NATIONAL {
  REQUEST = 'GET_DATA_NATIONAL_REQUEST',
  SUCCESS = 'GET_DATA_NATIONAL_SUCCESS',
  FAILURE = 'GET_DATA_NATIONAL_FAILURE',
}