export enum GET_VERSION_APP {
  REQUEST = 'GET_VERSION_APP_REQUEST',
  SUCCESS = 'GET_VERSION_APP_SUCCESS',
  FAILURE = 'GET_VERSION_APP_FAILURE',
}

export enum UPDATE_VERSION_APP {
  REQUEST = 'UPDATE_VERSION_APP_REQUEST',
  SUCCESS = 'UPDATE_VERSION_APP_SUCCESS',
  FAILURE = 'UPDATE_VERSION_APP_FAILURE',
}
