// lấy app version
export enum GET_WALLET_VERSION {
  REQUEST = 'GET_WALLET_VERSION_REQUEST',
  SUCCESS = 'GET_WALLET_VERSION_SUCCESS',
  FAILURE = 'GET_WALLET_VERSION_FAILURE',
  REFRESH = 'GET_WALLET_VERSION_REFRESH',
}

export enum UPDATE_WALLET_VERSION {
  REQUEST = 'UPDATE_WALLET_VERSION_REQUEST',
  SUCCESS = 'UPDATE_WALLET_VERSION_SUCCESS',
  FAILURE = 'UPDATE_WALLET_VERSION_FAILURE',
  REFRESH = 'UPDATE_WALLET_VERSION_REFRESH',
}

// lấy danh sách ngân hàng
export enum GET_BANK_LIST {
  REQUEST = 'GET_BANK_LIST_REQUEST',
  SUCCESS = 'GET_BANK_LIST_SUCCESS',
  FAILURE = 'GET_BANK_LIST_FAILURE',
  REFRESH = 'GET_BANK_LIST_REFRESH',
}

// lấy danh sách ngân hàng
export enum UPDATE_BANK {
  REQUEST = 'UPDATE_BANK_REQUEST',
  SUCCESS = 'UPDATE_BANK_SUCCESS',
  FAILURE = 'UPDATE_BANK_FAILURE',
  REFRESH = 'UPDATE_BANK_REFRESH',
}

// lấy danh sách nhà phát hành
export enum GET_ISSUER_LIST {
  REQUEST = 'GET_ISSUER_LIST_REQUEST',
  SUCCESS = 'GET_ISSUER_LIST_SUCCESS',
  FAILURE = 'GET_ISSUER_LIST_FAILURE',
  REFRESH = 'GET_ISSUER_LIST_REFRESH',
}
export enum ADD_ISSUER {
  REQUEST = 'ADD_ISSUER_REQUEST',
  SUCCESS = 'ADD_ISSUER_SUCCESS',
  FAILURE = 'ADD_ISSUER_FAILURE',
  REFRESH = 'ADD_ISSUER_REFRESH',
}
export enum UPDATE_ISSUER {
  REQUEST = 'UPDATE_ISSUER_REQUEST',
  SUCCESS = 'UPDATE_ISSUER_SUCCESS',
  FAILURE = 'UPDATE_ISSUER_FAILURE',
  REFRESH = 'UPDATE_ISSUER_REFRESH',
}

// lấy danh sách nhà cung cấp
export enum GET_SUPPLIER_LIST {
  REQUEST = 'GET_SUPPLIER_LIST_REQUEST',
  SUCCESS = 'GET_SUPPLIER_LIST_SUCCESS',
  FAILURE = 'GET_SUPPLIER_LIST_FAILURE',
  REFRESH = 'GET_SUPPLIER_LIST_REFRESH',
}

export enum ADD_SUPPLIER {
  REQUEST = 'ADD_SUPPLIER_REQUEST',
  SUCCESS = 'ADD_SUPPLIER_SUCCESS',
  FAILURE = 'ADD_SUPPLIER_FAILURE',
  REFRESH = 'ADD_SUPPLIER_REFRESH',
}
export enum UPDATE_SUPPLIER {
  REQUEST = 'UPDATE_SUPPLIER_REQUEST',
  SUCCESS = 'UPDATE_SUPPLIER_SUCCESS',
  FAILURE = 'UPDATE_SUPPLIER_FAILURE',
  REFRESH = 'UPDATE_SUPPLIER_REFRESH',
}

export enum GET_SETTING_ADVANCE_SYSTEM {
  REQUEST = 'GET_SETTING_ADVANCE_REQUEST',
  SUCCESS = 'GET_SETTING_ADVANCE_SUCCESS',
  FAILURE = 'GET_SETTING_ADVANCE_FAILURE',
}

export enum UPDATE_SETTING_ADVANCE_SYSTEM {
  REQUEST = 'UPDATE_SETTING_ADVANCE_REQUEST',
  SUCCESS = 'UPDATE_SETTING_ADVANCE_SUCCESS',
  FAILURE = 'UPDATE_SETTING_ADVANCE_FAILURE',
}

export enum GET_COOPBANK_LIST {
  REQUEST = 'GET_COOPBANK_LIST_REQUEST',
  SUCCESS = 'GET_COOPBANK_LIST_SUCCESS',
  FAILURE = 'GET_COOPBANK_LIST_FAILURE',
  REFRESH = 'GET_COOPBANK_LIST_REFRESH',
}
export enum ADD_COOPBANK {
  REQUEST = 'ADD_COOPBANK_REQUEST',
  SUCCESS = 'ADD_COOPBANK_SUCCESS',
  FAILURE = 'ADD_COOPBANK_FAILURE',
  REFRESH = 'ADD_COOPBANK_REFRESH',
}
export enum UPDATE_COOPBANK {
  REQUEST = 'UPDATE_COOPBANK_REQUEST',
  SUCCESS = 'UPDATE_COOPBANK_SUCCESS',
  FAILURE = 'UPDATE_COOPBANK_FAILURE',
  REFRESH = 'UPDATE_COOPBANK_REFRESH',
}
