export enum GET_LINKED_BANK_LIST {
  REQUEST = 'GET_LINKED_BANK_LIST_REQUEST',
  SUCCESS = 'GET_LINKED_BANK_LIST_SUCCESS',
  FAILURE = 'GET_LINKED_BANK_LIST_FAILURE',
  REFRESH = 'GET_LINKED_BANK_LIST_REFRESH',
}
