export enum GET_EWALLET_KYC {
  REQUEST = 'GET_EWALLET_KYC_REQUEST',
  SUCCESS = 'GET_EWALLET_KYC_SUCCESS',
  FAILURE = 'GET_EWALLET_KYC_FAILURE',
}

export enum UPDATE_EWALLET_KYC {
  REQUEST = 'UPDATE_EWALLET_KYC_REQUEST',
  SUCCESS = 'UPDATE_EWALLET_KYC_SUCCESS',
  FAILURE = 'UPDATE_EWALLET_KYC_FAILURE',
}

export enum REQUEST_EWALLET_KYC {
  REQUEST = 'REQUEST_EWALLET_KYC_REQUEST',
  SUCCESS = 'REQUEST_EWALLET_KYC_SUCCESS',
  FAILURE = 'REQUEST_EWALLET_KYC_FAILURE',
}

export enum REJECT_EWALLET_KYC {
  REQUEST = 'REJECT_EWALLET_KYC_REQUEST',
  SUCCESS = 'REJECT_EWALLET_KYC_SUCCESS',
  FAILURE = 'REJECT_EWALLET_KYC_FAILURE',
}

export enum GET_LOGS_EWALLET_KYC {
  REQUEST = 'GET_LOGS_EWALLET_KYC_REQUEST',
  SUCCESS = 'GET_LOGS_EWALLET_KYC_SUCCESS',
  FAILURE = 'GET_LOGS_EWALLET_KYC_FAILURE',
}

export enum REQUEST_APRROVAL_AUTO_EWALLET_KYC {
  REQUEST = 'REQUEST_APRROVAL_AUTO_EWALLET_KYC_REQUEST',
  SUCCESS = 'REQUEST_APRROVAL_AUTO_EWALLET_KYC_SUCCESS',
  FAILURE = 'REQUEST_APRROVAL_AUTO_EWALLET_KYC_FAILURE',
}

export enum REJECT_EWALLET_KYC_IC {
  REQUEST = 'REJECT_EWALLET_KYC_IC_REQUEST',
  SUCCESS = 'REJECT_EWALLET_KYC_IC_SUCCESS',
  FAILURE = 'REJECT_EWALLET_KYC_IC_FAILURE',
}

export enum REQUEST_EWALLET_KYC_IC {
  REQUEST = 'REQUEST_EWALLET_KYC_IC_REQUEST',
  SUCCESS = 'REQUEST_EWALLET_KYC_IC_SUCCESS',
  FAILURE = 'REQUEST_EWALLET_KYC_IC_FAILURE',
}
