
export enum GET_LIST_WITHDRAW {
    REQUEST = 'GET_LIST_WITHDRAW_REQUEST',
    SUCCESS = 'GET_LIST_WITHDRAW_SUCCESS',
    FAILURE = 'GET_LIST_WITHDRAW_FAILURE',
}

export enum CHANGE_WITHDRAW {
    REQUEST = 'CHANGE_WITHDRAW_REQUEST',
    SUCCESS = 'CHANGE_WITHDRAW_SUCCESS',
    FAILURE = 'CHANGE_WITHDRAW_FAILURE',
}